### ISSUE TITLE
Built-in accounts required for private chain?

### ISSUE THREAD

**Issue by phiferd** [ethereum/wiki#102]
Running parity version: Parity/v1.3.2-beta-e298ab3-20160929/x86_64-windows-msvc/rustc1.10.0

I tried to set up my own private chain, using the documentation on the wiki here: 
https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format

As far as I can tell, there is no explanation of the builtin accounts in any documentation.  I removed them without realizing they are required, and was able to get a chain up and running.  However, I noticed some very strange behavior: a simple "HelloWorld" contract that returned a string would not work (the return value was always "").  There were no errors during contract deployment and no errors when calling the helloWorld() method.

Steps to reproduce:
- Download the version of parity shown above
- Create a copy of the Morden chain config shown in the wiki linked above, modified to remove the builtin accounts
- Start the chain and a miner (pointed at a clean datadir)

```
parity --chain "~\private-net\chain\private-chain.json" --datadir "~\private-net\db" --geth --keys-path "~\private-net\keys" --signer-path "~\private-net\signer" --no-import-keys
```
- deploy a contract through Mist.

```
contract Hello {
    function getString() constant returns (string) {
        return "hello";
    }
}
```
- watch the contract in the parity UI or in Mist
- Note that no value is ever returned for the `getString()` function

By some luck, I was able to narrow down the issue to the exclusion of the built in accounts.  One or all of the following would be very helpful:
1. If these are required, add documentation.  
2. If a chain is started without the required account settings, thrown an exception at startup
3. If for some reason the required contracts are not available during execution, log something (preferably at a high log level)

**Comment by keorn** [comment]
These are implicitly added in Geth, while Parity requires explicit mention. We will improve the Parity documentation to reflect that.
