### ISSUE TITLE
Create Support for Language Brazilian portuguese

### ISSUE THREAD

**Issue by EvertonMelo** [ethereum/wiki#103]
how do I have to draw the wiki from English to Portuguese?

I want to help in translation but I have no permission to create the directory.

**Comment by EvertonMelo** [comment]
@drcode 
@janx 
@fjl 
@caktux 
@fbehrens 

maybe you have other priorities,
but by gentilza I would be able to know if he has an interest in doing this or not.

I can help, if you will.

**Comment by EvertonMelo** [comment]
@jamesray1 

very professional, closed without action.

this issue will be reopened.

**Comment by alexvandesande** [comment]
@EvertonMelo James was closing lots of old issues. We don't have current multilingual support but I highly recommend you do start a Brazilian wiki

**Comment by jamesray1** [comment]
@EvertonMelo please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for context.

**Comment by jamesray1** [comment]
You can create pages in wiki/wiki for a Brazilian wiki. Have a look at other languages for examples of the format (for instance, prepend filenames with [brasileiro], and add a link to Brazilian pages to the footer of the wiki.

**Comment by jamesray1** [comment]
We are not using the repo any more.

**Comment by EvertonMelo** [comment]
@alexvandesande 
The url:
https://github.com/ethereum/wiki/wiki ( en || pt-br ) 
do not meet this demand.
1º) does not contain physical files 
2º) does not have change control 
3º) does not have changeLog:
see it:
https://pt.wikipedia.org/w/index.php?title=Ethereum&action=history
( wikipedia has a better control than the official project, does this make sense? )

**Comment by EvertonMelo** [comment]
@jamesray1 

spare me of your apologies. 
this topic was opened in out/2016, 
the new policy is something recent.
https://github.com/ethereum/wiki/issues/589
( including the documents you give as a reference. )

@jamesray1  you were irresponsible and anachronistic. 
if you do not have the competence to explain what you are doing, let others do it.

**Comment by evertonfraga** [comment]
Hi @EvertonMelo.

@jamesray1 is a community member that recently brought many contributions to the wiki and documentation, which were severely outdated, without proper care. He's not the bad guy here.

It seems that github wiki was the chosen method to maintain a living document. I was not part of the decision-making process but among pros and cons, edit a wiki page is easier than sending pull requests.

**Comment by jamesray1** [comment]
@EvertonMelo if you don't llike wiki/wiki, you could try moving the content of it to https://www.quora.com/Whats-a-good-host-for-a-wiki-site-that-has-watch-ability-for-pages-with-email-notifications-for-changes-and-compatibility-with-GitHub-Flavoured-Markdown, then it could be maintained from there and wiki/wiki could be deprecated.
