### ISSUE TITLE
json rpc error code 32600

### ISSUE THREAD

**Issue by franklili3** [ethereum/wiki#116]
When I run "geth --rpc --rpccorsdomain "http://localhost:8545" --dev" , the server is starting. Then I open another cmd, and  run "curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://localhost:8545", the error is 
"{"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid character '\\'' looking for beginning of value"}}". How can I do?

**Comment by ashlesh688** [comment]
I am also facing the same issue
