### ISSUE TITLE
miner_start and miner_stop documentation for JSON-RPC

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/wiki#119]
This seems to be implemented in geth and ethereum-testrpc. Can we get some documentation in the JSON-RPC spec?

**Comment by mawalker** [comment]
Unfortunately, Ethereum Documentation is more than a little lacking when it comes to logical organization(at least to me, they could do with better cross referencing at the very least). 

There already is documentation for what you are asking, however they have decided to split up the API for JSON-RPC and the rest of the.... 'management APIs' However, only the Management APIs page makes reference of this... so if you start looking from the JSON-RPC page.... good luck....

The link here is to the geth (go) implementation, but this should be what you are looking for. 

[https://github.com/ethereum/wiki/wiki/JSON-RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC)

[https://github.com/ethereum/go-ethereum/wiki/Management-APIs](https://github.com/ethereum/go-ethereum/wiki/Management-APIs)
