### ISSUE TITLE
yellow paper file 404 not found

### ISSUE THREAD

**Issue by khassan0v** [ethereum/wiki#120]
At https://github.com/ethereum/wiki/wiki#getting-started
link http://gavwood.com/Paper.pdf
![1](https://cloud.githubusercontent.com/assets/833019/21184139/214af032-c21c-11e6-8bfd-24d9192795e0.png)

**Comment by khassan0v** [comment]
File is available by the link.

**Comment by motatoes** [comment]
Correct link is http://paper.gavwood.com/
