### ISSUE TITLE
Provided Host header is not whitelisted error on curl call.

### ISSUE THREAD

**Issue by ChloeCoupignyWarot** [ethereum/wiki#126]
When I do this command : 
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_coinbase","params":[],"id":64}' http://xxx.xxxx.xxx.xxx:8545` 

i've this error : 
`Provided Host header is not whitelisted`

What does it means?

**Comment by mingderwang** [comment]
COOL, I have the same problem.
