### ISSUE TITLE
the Ethereum main wiki has lost its Navigation directory

### ISSUE THREAD

**Issue by sportshark** [ethereum/wiki#136]
the Ethereum main wiki has lost its Navigation directory，when i go to the Ethereum main wiki , it only show all the pages  include english、chinese and so on, it  has be classified in the past and has a catalog

**Comment by cdetrio** [comment]
Thanks. Somebody [deleted](https://github.com/ethereum/wiki/wiki/_compare/1f5ef515d58edbc4d8168163f1b3d59939545d45...6260d84ca7904e02f86956effefa5124b94df3e9) the _Sidebar.md file. That change is now [reverted](https://github.com/ethereum/wiki/wiki/_compare/6e4ac12a86352002059b4a6a33157cac9f5f0592...be187237bf7479a266770b3f9eb5d1b11a370cbe).
