### ISSUE TITLE
methode to list all transaction of an account ? 

### ISSUE THREAD

**Issue by lbrth** [ethereum/wiki#139]
Somebody knows if there is actually a way to easily listed all transactions of an account/address or if this method is in work in progress ? 

like:  `web3.eth.getTransactionList(address) `

Thanks !

output : all transactions hash for `web3.eth.account[x] `

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
