### ISSUE TITLE
Clarify which variables can be written

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/wiki#14]
For example, I was expecting the following command `eth.mining = true` to start mining.

**Comment by LianaHus** [comment]
https://github.com/ethereum/cpp-ethereum/wiki/Using-Ethereum-CLI-Client

**Comment by LianaHus** [comment]
https://github.com/ethereum/guide/blob/master/mining.md

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed, although the issue seems to have been addressed, answered or resolved.
