### ISSUE TITLE
`constant` functions  for Solidity not documented

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/wiki#19]

**Comment by chriseth** [comment]
They are documented here: https://github.com/ethereum/wiki/wiki/Solidity-Tutorial#modifiers

**Comment by aakilfernandes** [comment]
They are documented for state variables, not functions

**Comment by JeffreyBPetersen** [comment]
There doesn't look to be any easily accessible and thorough documentation on them at the moment. http://solidity.readthedocs.io/en/latest/frequently-asked-questions.html#what-is-the-difference-between-a-function-marked-constant-and-one-that-is-not is the most I could find with some quick searching around.

**Comment by chriseth** [comment]
It's both there: http://solidity.readthedocs.io/en/latest/miscellaneous.html#modifiers

And it more or less says that it is currently ignored for functions.

**Comment by JeffreyBPetersen** [comment]
Ah, thank you. This issue thread came up while searching so that makes the details a lot easier to find now.
