### ISSUE TITLE
"log topic" in Solidity Tutorial

### ISSUE THREAD

**Issue by taoeffect** [ethereum/wiki#23]
Was trying to figure out what `indexed` meant, but [Solidity Tutorial](https://github.com/ethereum/wiki/wiki/Solidity-Tutorial) does not explain what a "log topic" is.

**Comment by LianaHus** [comment]
moved to solidity repo

**Comment by LianaHus** [comment]
moved to solidity repo

**Comment by LianaHus** [comment]
for now you can check out Yellow Paper http://gavwood.com/paper.pdf
for ex. line 2, 28-32
