### ISSUE TITLE
[BUG] Browser Solidity compiler crashes on two devs computers.

### ISSUE THREAD

**Issue by cozylife** [ethereum/wiki#26]
The [browser Solidity compiler](https://chriseth.github.io/browser-solidity/) crashes when running on Chrome through two different computers. I'm on Windows 10 and my coworker is on Linux. The code in question is as follows.

```
contract c
{
    function test() public returns(uint8)
    {
        uint8[] testing;
        testing[testing.length++] = 1;
        testing[testing.length++] = 2;
        testing[testing.length++] = 3;
        
        delete testing[1];
        
        uint8[] testing1;
        for (uint8 i = 0; i < testing.length; i++) {
            if (0 != testing[i]) {
                testing1[testing1.length++] = testing[i];
            }
        }
        
        return testing1[0];
    }
}
```
**Steps to reproduce**
1. Create the contract.
2. Click the "test" button to run the code.
3. Watch the tab in Chrome crash after hanging for a bit.

**Comment by LianaHus** [comment]
I'll move the issue to solidity repository.

**Comment by LianaHus** [comment]
https://github.com/ethereum/solidity/issues/44
