### ISSUE TITLE
How to run Arm binary

### ISSUE THREAD

**Issue by codecowboy** [ethereum/wiki#29]
I downloaded the pre built arm binary to run on Ubuntu Mate (Raspberry Pi 2). I ran chmod +x and then ./geth but get:

`bash: ./geth: No such file or directory`

What am I missing?

**Comment by geraudster** [comment]
Same problem on arm7 hardware with Ubuntu 14.04 and 15.10. I've had to recompile geth following instructions from https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu#building-from-source

Then I saw the following difference between both executable:

    $ file ./build/bin/geth # my compiled version
    ./build/bin/geth: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked,  interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32,  BuildID[sha1]=2113d35b8179e7e88effeb58cc4ef42be6a7135d, not stripped
    
    $ file geth # downloaded build
    geth: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=d8531c0fe57d503d426dc1a97fde470d6c5f4eea, not stripped


The interpreter is different, so creating a symlink will make the original build work:
`ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3`

**Comment by evilsocket** [comment]
added to the known issues https://github.com/bettercap/bettercap/wiki/Known-Issues#bash-usrlocalbinbettercap-no-such-file-or-directory
