### ISSUE TITLE
JSON-RPC serve examples don't work

### ISSUE THREAD

**Issue by dbabits** [ethereum/wiki#35]
I am always getting one of these 2 errors below no matter which RPC function i try.
What am i doing wrong?

root@58fe424912ee:/# geth --datadir /tmp/eth/42 --port 30303 --password <(echo -n notsosecret) --unlock 0 --rpcport 8545 &

[ec2-user@ip-172-31-38-111 download]$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://127.0.0.1:8545
curl: (56) Recv failure: Connection reset by peer

[ec2-user@ip-172-31-38-111 bank.js]$ curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}' http://127.0.0.1:8545  
curl: (52) Empty reply from server

**Comment by Tzunami** [comment]
the --datadir should be an empty directory. You have it going to a folder called "42"
# geth --datadir /tmp/eth/42

**Comment by dbabits** [comment]
so? it is an empty directory.

**Comment by Tzunami** [comment]
your --datadir should point to an empty directory. Once run initialized files will pop up in that folder.
To answer you question.. Yes

**Comment by dbabits** [comment]
@Tzunami, my /tmp/eth/42 IS an empty directory! 
I don't think it has anything to do with my question.
Thank you for trying to help anyway.
