### ISSUE TITLE
'Access-Control-Allow-Origin' error, DAPP Using Meteor page 

### ISSUE THREAD

**Issue by HiroIshikawa** [ethereum/wiki#36]
I followed the instructions but when I run the javascript console on the Meteor site on localhost:3000, I got an error message below.

> '“XMLHttpRequest cannot load http://localhost:8545/. Response to preflight request doesn't pass access >control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin >'http://localhost:3000' is therefore not allowed access.”'

I chanaged the command 
`$ geth --rpc --rpccorsdomain “http://localhost:3000`
to 
`$ geth --rpc --rpcaddr="localhost" --rpcport="8545" --rpccorsdomain="http://localhost:3000"`
and `> web3.eth.accounts`shows the accounts in the network successfully.

Should we modify it, if this is replicable for others too?

**Comment by psmadja** [comment]
Hello, 
I have the same issue with geth version 1.4.0
receiving /OPTIONS,   geth does not return  "Access-Control-Allow-Origin" header
 --rpccorsdomain="http://localhost:3000"
I tried with --rpccorsdomain  "http://*"
with --rpccorsdoamin '"*"'     I saw also  this syntax somewhere

what is the correct syntax
Thanks
Philippe

**Comment by psmadja** [comment]
Hello,
Access-Control-Allow-Origin   header is sent using the  syntax    --rpccorsdomain="*" 
Cheers,
Philippe.

**Comment by hiddentao** [comment]
Just a note that multiple CORS domains are supported, e.g. `--rpccorsdomain="http://localhost:9090 http://localhost:8080" `

**Comment by Levino** [comment]
The docs are wrong here.  ```geth --rpc --rpccorsdomain "http://localhost:3000"``` must be ```geth --rpc --rpccorsdomain="http://localhost:3000"``` Not?

**Comment by bellaj** [comment]
> Just a note that multiple CORS domains are supported, e.g. --rpccorsdomain="http://localhost:9090 http://localhost:8080"

separated by ,
`--rpccorsdomain "http://19.168.26.128,http://localhost:9090,http://localhost:8080"`

**Comment by sc231985** [comment]
Any Ideas on this issue.

**Comment by raky35** [comment]
Hi,  i am also unable to connect local remix to local Mist ,  
- Web3 Provider Endpoint (http://localhost:8545) error: Not possible to connect to the Web3 provider. 
./geth --datadir=./chaindata/ --cache 1024 --ipcpath ~/Library/Ethereum/geth.ipc --rpc --rpcaddr=localhost –rpcport=8545 --rpcapi="db,eth,net,web3,personal"  --rpccorsdomain=localhost   --unlock 0 --mine 1

**Remix Error** : "Make sure the provider is running and a connection is open (via IPC or RPC).
 and 
**Browser error** : [Error] Failed to load resource: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin. (localhost, line 0)
[Error] XMLHttpRequest cannot load http://localhost:8545/. Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.
	send (app.js:195778)
	isConnected (app.js:195838)
	isConnected (app.js:194109)
	setProviderFromEndpoint (app.js:155831)
	(anonymous function) (app.js:207567)
	fn (app.js:208851)
	okListener (app.js:208896)

Please accept my apologies for any ignorance. 
Thanks, 
Kind Regards,
raky

**Comment by subhodi** [comment]
@raky35  instead of command line try the following from geth console
```javascript
admin.startRPC("0.0.0.0",8545, "*", "web3,eth,db,net");
```
Thrid argument `*` refers to whitelist all.
You can automate this by loading javascript to geth through command line.

**Comment by jamesray1** [comment]
Belated reason for why this was closed: https://github.com/ethereum/wiki/wiki#issues-and-pull-requests.
