### ISSUE TITLE
Ethereum White-paper link. 

### ISSUE THREAD

**Issue by androlo** [ethereum/wiki#39]
The link at 21 - Peter Todd on Merkle sum trees - under [Further Reading](https://github.com/ethereum/wiki/wiki/White-Paper#further-reading) appears to be dead.

**Comment by bitspill** [comment]
Replaced with a link to the relevant archive.org link. https://web.archive.org/web/20140623061815/http://sourceforge.net/p/bitcoin/mailman/message/31709140/
