### ISSUE TITLE
Link to Image file not working

### ISSUE THREAD

**Issue by geoster** [ethereum/wiki#40]
I've been trying to download from http://gav.ethdev.com/ArchLinuxEthereum12082015.img.zip since Friday with no luck. Is there a new location to get the image? Thanks!

**Comment by LianaHus** [comment]
@LefterisJP ?

**Comment by bobsummerwill** [comment]
Yeah - you don't want to do that, @geoster, though you probably aren't "doing that" anymore looking at the age of this issue :-)

AUR details ->
http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/linux-arch-aur.html

Which page had that link, @geoster?

**Comment by geoster** [comment]
Yeah, I gave up on trying to get it working on raspberry pi and moved on to other things.

@bobsummerwill I don't remember anymore. It was probably here: https://github.com/ethereum/wiki/wiki/Raspberry-Pi-instructions though it looks like you updated that page last month.

**Comment by LefterisJP** [comment]
no, those images are no longer maintained I think

**Comment by bobsummerwill** [comment]
No - they're not.

And this Raspberry Pi Wiki page also needs removing when I get the chance.

All-new docs at http://ethdocs.org, Geoff!

See also http://ethembedded.com/.
