### ISSUE TITLE
Ethereum (centralised) network status monitor down

### ISSUE THREAD

**Issue by esetnik** [ethereum/wiki#401]
https://stats.ethdev.com/
ERR_CONNECTION_TIMED_OUT

**Comment by karalabe** [comment]
https://ethstats.net/

**Comment by jamesray1** [comment]
Make sure you update where you saw the link.

Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed, although the issue seems to have been addressed, answered or resolved.
