### ISSUE TITLE
Ethereum Mist Wallet never get complete sync

### ISSUE THREAD

**Issue by plizer** [ethereum/wiki#402]
Hi!

I really hope someone can help me here. I already invested about 30 hours to fix the problem and dont know what to do anymore :(

No matter what I do, I dont get a full sync. There are always 100 to 300 blocks left. The balance is 0.00 ether. I hope that problem will fixed when I have the full sync.

What could be the problem here?

I would be SO happy to get any comment to this!

Thanks alot!

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
