### ISSUE TITLE
The method eth_getCompilers does not exist/is not available

### ISSUE THREAD

**Issue by dream960727** [ethereum/wiki#403]
Error: The method eth_getCompilers does not exist/is not available
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
what should i do if i want to get the compiler?
And there are other function have this problem like eth.compile.solidity()
> eth.compile.solidity
function()
> eth.compile.solidity(source)
Error: The method eth_compileSolidity does not exist/is not available
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

**Comment by aboynejames** [comment]
this also happen to my install on latest update from geth

> web3.eth.getCompilers()
Error: The method eth_getCompilers does not exist/is not available
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

**Comment by promethe42** [comment]
+1

**Comment by swaldman** [comment]
See https://github.com/ethereum/EIPs/issues/209

**Comment by amrikmahal** [comment]
Please fix this in the next release.  Let us know by when can this fixed.  Similar issues being discussed here also
https://github.com/ethereum/go-ethereum/issues/3793

**Comment by rcarubbi** [comment]
+1

**Comment by john04047210** [comment]
What is the solution of the problem?Thanks very much.

**Comment by ccbytes** [comment]
Same problem here on Geth/v1.8.17-stable-8bbe7207/linux-amd64/go1.10
