### ISSUE TITLE
while geth is running i open mist but instead of being attached to geth mist restart sync from scratch

### ISSUE THREAD

**Issue by back2flash** [ethereum/wiki#405]
hello i hope i can get some help, after 2 weeks of trying i'm about to give up it's like the 5th time i try sync from scratch every time there was some problem. now geth --fast is finally running ok and i wanted to see the progress bar of sync in mist so i open mist 1st time no problem exept error in geth terminal RPC/server.go:371 write unix / users/my path/library/ethereum/geth.ipc-> write: broken pipe. 
i close mist . an hour later i restart mist for the same reason but i see that mist begins to sync from scratch. normally when geth is running the mist should attach on geth and show the sync progress. 
after searching i saw in a post that if mist can't find the previous data, mist start an other geth protocol and begin to sync from scratch and the 2 geth protocols at the same time is no good.  How can i let mist make the link to the right files when starting the program ?
geth --fast is still running , and i closed mist for now . when geth --fast is finished i would like to fix the problem with mist rather then another time remove db  and sync from scratch . i looked everywhere first but didn't find an answer on my question ,  thanx in advance

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
