### ISSUE TITLE
Connecting to Morden Testnet

### ISSUE THREAD

**Issue by tejasriram** [ethereum/wiki#408]
I was trying to connect to morden testnet as mentioned in this link, https://github.com/ethereum/wiki/wiki/Morden

I am using a geth client, so I tried to connect using geth --testnet console.

I looked up on the link, https://github.com/ethereum/wiki/wiki/Morden for genesis block hash and some other parameters, and they don't match the output of eth.getBlock(0). Why is there a mismatch, Where am I going wrong?

I am using Geth 1.6.0 and go version 1.8.1
![testnet](https://cloud.githubusercontent.com/assets/26278822/25571977/b2d2bf96-2e53-11e7-9708-5bfd2acad1c8.png)

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
