### ISSUE TITLE
Unable to send custom token

### ISSUE THREAD

**Issue by alfa1983** [ethereum/wiki#410]
Hi. 
I`ve created a custom token following the Ethereum in practice part 1 guide.
Everithing is awesome exept I cant send them as they are not displayed as a payment option in my wallet.
![eth1](https://cloud.githubusercontent.com/assets/28307185/25627477/61022dbe-2f6b-11e7-9b2c-050d04e0d6a5.png)
![eth2](https://cloud.githubusercontent.com/assets/28307185/25627486/67b3df4a-2f6b-11e7-9474-835bb9a5a794.png)
![eth3](https://cloud.githubusercontent.com/assets/28307185/25627495/6aaaad78-2f6b-11e7-94b6-5354cd1bae80.png)

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
