### ISSUE TITLE
Intended behavior of batch requests

### ISSUE THREAD

**Issue by Zanibas** [ethereum/wiki#411]
In the web3 documentation:
```
Batch requests

Batch requests allow queuing up requests and processing them at once.

Note Batch requests are not faster! In fact making many requests at once will in some cases be faster, as requests are processed asynchronous. Batch requests are mainly useful to ensure the serial processing of requests.
```

But here in the JSON-RPC 2.0 Spec:
http://www.jsonrpc.org/specification#batch
```
The Server MAY process a batch rpc call as a set of concurrent tasks, processing them in any order and with any width of parallelism.
```

Thus, it seems there are two different ideas floating around with how to implement batch. Should the API then be modified to remove this mention of serial processing or should providers modify their behavior to ensure serial processing?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
