### ISSUE TITLE
Minimum Go version? 1.7 or 1.8?

### ISSUE THREAD

**Issue by kedoska** [ethereum/wiki#412]
[Here](https://github.com/ethereum/go-ethereum/blame/master/README.md#L19) you have this definition 
> Building geth requires both a Go (version 1.7 or later) and a C compiler...

[Here](https://github.com/ethereum/go-ethereum/wiki/Developers'-Guide) this other definition
> We assume that you have go v1.8 installed, and GOPATH is set.

By following the Developers' Guide, the instruction is to:
`curl -O https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz`

**Comment by junjizhi** [comment]
I had the same question here. I was able to build geth with go v1.7 on Ubuntu 17. Not sure about what's missing in go 1.7 compared with go v1.8.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
