### ISSUE TITLE
Deposit BTC to Ethereum Wallet and Still no ETH

### ISSUE THREAD

**Issue by rivaderci88** [ethereum/wiki#413]
I recently downloaded a wallet from ethereum.org and transferred 1 btc to the address my ethereum wallet populated when I selected the "fund with bitcoin method" 

It specifically said send to address "xxxxxxxxxx" we will convert the bitcoin to 16.9 ethereum and send it to your wallet address

The transactoin shows as complete in my coinbase but I do not see the Ethereum in my account.

Is there any reason this is happening?  Do I have any recourse?

**Comment by jeffanthony** [comment]
This is not an issue with Ethereum nor a the Ethereum wiki. However you use the term 'coinbase.' Are you referring to the company at the .com of the same name? If so, they are the ones to chat with about your services; however, sending BTC to the ethereum network is not possible without exchanging it. I don't believe Coinbase does this (if you, in fact, are talking about them) without making you go over to their GDAX to trade.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
