### ISSUE TITLE
Can't install Mist: hi guys, "Your node is currently on the unsupported Ethereum Classic chain"

### ISSUE THREAD

**Issue by firecentaur** [ethereum/wiki#416]
Hi everyone, when I try to install mist, I get an error:

> Your node is currently on the unsupported Ethereum Classic chain
>  To use this chain use tools provided by the ethereum classic project at https://ethereumclassic.github.io.  To revert to the main ethereum chain follow the tutorial here: https://github.com/ethereum/mist/releases/0.8.2
> 

However, there is no tutorial at the link specified

**Comment by firecentaur** [comment]
Hi, I managed to fix the issue by searching for everything named Mist, and deleting. (Of course AFTER backing up my key store)  However, the download page needs to be fixed because the error message leads people to the https://github.com/ethereum/mist/releases/0.8.2 page, but there is NO tutorial there

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed, although the issue seems to have been resolved.
