### ISSUE TITLE
fatal error: out of memory

### ISSUE THREAD

**Issue by PaulieD** [ethereum/wiki#417]
Launching and dealing with this eth wallet for first time. It wont sync. node.log shows a fatal error: out of memory
[node.log.txt](https://github.com/ethereum/wiki/files/981274/node.log.txt)

**Comment by PaulieD** [comment]
I have for over 10 hours straight been trying to sync with no progress.

**Comment by deejbee** [comment]
+1 

I'm getting the same error.  I have a 16Gb machine and task manager is showing lots available.  I have been trying to use Ethereum for the first time (Windows) by just running **Ethereum Wellet.exe**.  In task manager I can see the 4 wallet processes running and also the Geth.exe which runs for a while and is downloading Chain structure but then Geth.exe suddenly terminates with the following:
```
INFO [06-13|16:33:16] Imported new state entries               count=3    elapsed=14.000ms  processed=206793 pending=28723
INFO [06-13|16:33:16] Imported new state entries               count=384  elapsed=12.000ms  processed=207177 pending=28414
INFO [06-13|16:33:16] Imported new state entries               count=3    elapsed=1.000ms   processed=207180 pending=28406
INFO [06-13|16:33:16] Imported new state entries               count=165  elapsed=4.000ms   processed=207345 pending=28237
runtime: out of memory: cannot allocate 134217728-byte block (948699136 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xc6c852, 0xd)
	C:/go/src/runtime/panic.go:596 +0x7c
runtime.largeAlloc(0x8000000, 0x1e80001, 0x44c033)
	C:/go/src/runtime/malloc.go:809 +0xdb
runtime.mallocgc.func1()
	C:/go/src/runtime/malloc.go:702 +0x31
runtime.systemstack(0x12117500)
	C:/go/src/runtime/asm_386.s:337 +0x5e
runtime.mstart()
	C:/go/src/runtime/proc.go:1132
```
The Ethereum UI doesn't do anything after that (no report of failure).  I'm not sure why it is trying to allocate a massive amount of continuous memory in the first place.  It seems to be a bug.

I notice from the geth.exe options that the --cache option has a default of 128MB but it is being launched using --cache 512  and by looking at task manager the process uses up to around 1GB before it terminates.

**Comment by catsgotmytongue** [comment]
I'm also running into this problem.

Have you had any luck with it?

Are you running windows 10 pro 64bit?
I am and I also have 16GB of ram and a 4GB NVIDIA GeForce GTX 970.

I'm not sure what the problem is but it does seem to be related to geth.exe getting to more than 1GB of memory

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
