### ISSUE TITLE
original whitepaper

### ISSUE THREAD

**Issue by benjyz** [ethereum/wiki#418]
looking for the december 2013 WP. this link breaks: https://twitter.com/vitalikbuterin/status/583269085137526784

**Comment by jamesray1** [comment]
Sep 1 2014: https://github.com/ethereum/wiki/wiki/White-Paper/08e9d07781f50dac264314a551b5ba060a07c06a.

This is the earliest version that I could find: https://github.com/ethereum/wiki/commit/4e77283d2eb30ff97fbc748f75d5d7d9fa55a341#diff-877199317d7fd18a833c1c8fb2eb02bc.

There's also https://github.com/ethereum/wiki/commits/d1f0e765fdb6abcbc96932694a5ae56dbd57a279/Old-Ethereum-Whitepaper.md.

Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.

**Comment by benjyz** [comment]
this has the history: https://vitalik.ca/general/2017/09/14/prehistory.html
