### ISSUE TITLE
RPi2 ReadyToUse Image not available

### ISSUE THREAD

**Issue by gregorvolkmann** [ethereum/wiki#42]
Foundation leadership shutdown server where the Ready2Use Image for the RPi2 is hosted. Mailed @gavofyork and @CJentzsch about this issue.

Any way to get the Image for the Raspberry?

Image is linked on this wiki page: https://github.com/ethereum/wiki/wiki/Raspberry-Pi-instructions

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.

Try to find someone who developed Raspberry Pi.
