### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by ligi** [ethereum/wiki#422]
https://github.com/ethereum/wiki/wiki/Light-client-protocol

uses

http://vitalik.ca/files/spv.png

unfortunately this image does not exist anymore. Would fix it instantly - but dunno where to find this image. Anyone still has the original and can give the hash?-)

**Comment by tashian** [comment]
@ligi the image below seems like it would fit with the text:

https://raw.githubusercontent.com/ethereumbuilders/GitBook/master/en/vitalik-diagrams/spv1.png

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed, although the issue seems to have been resolved.
