### ISSUE TITLE
Wallet resource missing fails to authorize account 

### ISSUE THREAD

**Issue by kiahmed** [ethereum/wiki#423]
My geth node is running fine but when try to add an account with mist it consistently fails with this error. wallet daap really missing this resource ? 
**Failed to load resource: the server responded with a status of 404 "https://wallet.ethereum.org/sockjs/info?cb=sasac9v7yd"**

tried all sort of things. Account is unlocked, also published all required api via --rpcapi . It just wont work both with mainnet and testnet. It is talking to a remote get node tho over rpc. What is wrong? It thats what it is did anyone try another browser/wallet with remote geth? Running geth locally is not an option for me

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
