### ISSUE TITLE
Ethereum Contract ABI - Encoding for functions with no arguments

### ISSUE THREAD

**Issue by trivikrama619** [ethereum/wiki#424]
I am using argument encoding from this page (https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI) to build data field for offline signing. I am using eth_sendRawTransaction to call a function in my deployed smart contract. Everything is working fine when the functions have arguments (1 or more), but I am getting an "invalid opcode" exception for the functions which have no arguments. I am using just the first four bytes of the function selector (i.e, sha3('myFunc()')) since there are no arguments.

These functions are working fine when I use a dummy argument (keeping the rest same). 

Is there a special way to handle functions without arguments ?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
