### ISSUE TITLE
Spam in wiki

### ISSUE THREAD

**Issue by mohamedziada** [ethereum/wiki#426]
This is spam in your wiki

https://github.com/ethereum/wiki/wiki/%D8%B4%D8%B1%D9%83%D8%A9-%D8%A7%D9%84%D9%85%D9%86%D8%A7%D8%B1%D8%A9

**Comment by ashishg-qburst** [comment]
Deleted.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed, although the issue seems to have been resolved.
