### ISSUE TITLE
Unable to locate transaction entry

### ISSUE THREAD

**Issue by georgeaga** [ethereum/wiki#430]
Hi, 
I sent 0.5 eth to an address that worked previously and now when i click on the tx has it says: Unable to locate Transaction entry
What can I do?
tx hash is: 0x8271301ac235d0bc4c3557efd9772fd1de9a8373845c775dcfa0d3ca356dfec9

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.

Also check the MyCrypto knowledge base.
