### ISSUE TITLE
Bogdan

### ISSUE THREAD

**Issue by bogdandocu** [ethereum/wiki#440]
I installed a wallet on ethereum.com and funded it through coninbase. Coinbase charged my credit card, it shows the transaction but my ethereum wallet is 0. Shows no incoming ether. Should I dispute the credit card charge? it's been a week now..
thanks!

**Comment by YitYeh** [comment]
I had a similar issue with Gemini. Wired money into my gemini account but
Gemini shows nothing. My bank has confirmed the wire went through though...

I'd love to hear about any ideas you come up with on how to handle this.
Can you email me at yehoshu@cooper.edu?

**Comment by bogdandocu** [comment]
Will do
