### ISSUE TITLE
Explanation needed for oracle contract in white paper

### ISSUE THREAD

**Issue by jamesray1** [ethereum/wiki#443]
The White Paper (in ethereum/wiki) states: 
> ...one powerful use case of an oracle contract...

Searching for oracle contract brings up results related to the company Oracle. More explanation (maybe as a link) for what an oracle contract as well as an oracle would be good.

**Comment by lastbutnotleast** [comment]
I believe that means a contract which needs external information not present in the contract itself nor the blockchain. The paragraph that statement is from explains how converting USD to BTC would require external data in a contract for an accurate conversion to occur at a given time, ~Dynamic external ratio.

**Comment by jamesray1** [comment]
Thanks, I added a note based on your explanation.
