### ISSUE TITLE
Explication needed in White Paper fees section

### ISSUE THREAD

**Issue by jamesray1** [ethereum/wiki#447]
https://github.com/ethereum/wiki/wiki/White-Paper#fees

Context:

> 1. A transaction leads to `k` operations, offering the reward `kR` to any miner that includes it where `R` is set by the sender and `k` and `R` are (roughly) visible to the miner beforehand.
> 2. An operation has a processing cost of `C` to any node (ie. all nodes have equal efficiency)

> 1. The miner does pay a higher cost to process the transaction than the other verifying nodes, since the extra verification time delays block propagation and thus increases the chance the block will become a stale.

> 2. There do exist non-mining full nodes.

> (1) provides a tendency for the miner to include fewer transactions, and (2) increases `NC`; hence, these two effects at least partially cancel each other out.

How do they partially cancel each other out? Be more explicit.

(1) C_miner > C_verifying node.  N*C_miner is more likely to be higher than `R`  so the miner will include fewer transactions. (2) Assume `N` is the total number of nodes so is higher with non-mining nodes, thus `NC` increases. I still struggle to see how they cancel each other out.

**Comment by Enigmatic331** [comment]
I too am having issues understanding this section of the whitepaper. Perhaps I am just missing something?

**Comment by foogunlana** [comment]
@jamesray1 @Enigmatic331  It's not 100% clear to me either but perhaps this could help:

(2) Means that not all nodes collect the reward, so while ```NC``` increases due to an increase in nodes, the reward per miner doesn't fall with each additional non-mining node.

I think the ambiguity comes from the inequality ```R < NC``` which is fine, but doesn't differentiate between ```Nm``` (miner), and ```Nn``` (non-miner).

Perhaps it should be something like ```R/Nm < (Nm + Nn)C``` ?
Do you think that helps?

**Comment by jamesray1** [comment]
Yeah I looked over it again and I am not sure if I still fully understand it. I think the effects partially cancel each other out because the miner pays a higher cost than non-miners to process each transaction, while there are non-mining full nodes, so the total network cost of processing each transaction also increases. Therefore, because the total network cost increasing also negatively impacts non-mining nodes (as well as miners being impacted by higher costs than non-mining full nodes), inequality in the network is minimised.

**Comment by jamesray1** [comment]
Well someone removed the "clarification needed" tag without doing anything about this issue.

**Comment by jamesray1** [comment]
I readded a "How?" tag.

**Comment by jamesray1** [comment]
@vbuterin may you please clarify this?

**Comment by gftea** [comment]
I think it may be due to below:
miner's expected reward is kR/N, the NC increase, so the sender has tendency to increase R, so (1) and (2) cancel each other

**Comment by mattbonnell** [comment]
To correct the minor typos in @foogunlana  formula:
`R/N_m > (N_m*C_m + N_n*C_n)/(N_m + N_n)`
