### ISSUE TITLE
Optional padding on web3 `fromAscii` method not implemented

### ISSUE THREAD

**Issue by FemiAw** [ethereum/wiki#450]
Passing a padding argument as a second parameter in `fromAscii` does not pad the hexadecimal as stated here in the web3 API [documentation](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3fromascii).  

> `var str2 = web3.fromAscii('ethereum', 32);` // Returns "0x657468657265756d" instead of the result padded

**Comment by aido179** [comment]
Having the same issue. web3 version 0.20.2
Expected:
```
> web3.fromAscii('ethereum', 32);
"0x657468657265756d000000000000000000000000000000000000000000000000"
```
Observed:
```
> web3.fromAscii('ethereum', 32);
"0x657468657265756d"
```

**Comment by lcdupree** [comment]
This still isn't fixed.

**Comment by jamesray1** [comment]
See https://github.com/ethereum/wiki/wiki#issues-and-pull-requests.
