### ISSUE TITLE
shh newIdentity() Function does not exist

### ISSUE THREAD

**Issue by karthiknvlr** [ethereum/wiki#453]
I am trying to send messages between nodes in ethereum private setup using whisper protocol, using shh.
This is my code 
``` nodejs
const Web3 = require('web3');
const solc = require('solc');
const shh = require('shh');
const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
var identity = web3.shh.newIdentity();
var topic = 'example';
var payload = 'hello whisper world!';

var message = {
  from: identity,
  topics: [topic],
  payload: payload,
  ttl: 100,
  workToProve: 100 // or priority TODO
};
 web3.shh.post(message);

```

While I try to run this It was showing error 
` 
Error: The method shh_newIdentity does not exist/is not available
`

**Comment by maroodb** [comment]
I faced the same error, is there a solution for that issue?

**Comment by ramkinavy** [comment]
Im getting same error JSON RPC

{
    "jsonrpc": "2.0",
    "id": 73,
    "error": {
        "code": -32601,
        "message": "The method shh_newIdentity does not exist/is not available"
    }
}
