### ISSUE TITLE
How do you convert 0.01 into this unit?

### ISSUE THREAD

**Issue by 18y** [ethereum/wiki#454]
![image](https://user-images.githubusercontent.com/22790765/28515922-fe7123ea-7091-11e7-8471-24c28dbeb2d7.png)

**Comment by yockii** [comment]
Convert 0.01 to ether units first ( 0.01 * 10.pow(18) ), then convert to Hexadecimal (that is start with 0x)

**Comment by 18y** [comment]
@yockii Thans, thats right!How do I check the transaction records now?I found no such interface

**Comment by yockii** [comment]
I use the eth_newFilter with schedued call eth_getFilterChanges, and than get the transaction use the return info of eth_getFilterChanges(transactionHash) to get transactions.
