### ISSUE TITLE
Couldn't connect to Ethereum Node

### ISSUE THREAD

**Issue by rivaderci88** [ethereum/wiki#460]
I AM GETTING THE FOLLOWING MESSAGE

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...INFO [08-19|16:04:09] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [08-19|16:04:09] Allocated cache and file handles         database=/Users/robertriva/Library/Ethereum/geth/chaindata cache=1024 handles=1024

What am I supposed to do?

**Comment by rivaderci88** [comment]
Any help would be appreciated

**Comment by Scorpion2185** [comment]
Try this, go to C:\Users\yourusername\AppData\Roaming\Ethereum\geth (or where is your chaindata folder) and delete, rename or move the chaindata folder. I rename it chaindata- backup. Now the wallet will start and it have to synchronize again everything. Then if it will be stuck in the latest blocks change the internet time to "time.nist.gov". Control panel--> Clock,Language...--> Date and time--> Internet time. And use the option in the wallet-->development light client. And if you have any further problem run geth before the wallet.
