### ISSUE TITLE
Ethereum software won't open

### ISSUE THREAD

**Issue by rivaderci88** [ethereum/wiki#461]
How is this ever going to become mainstream, when I want to access my "Wallet" and I get a series of numbers and letters telling me the "node cannot be found."

It's incredibly frustrating to feel as though you have to have a programming background to participate in cryptocurrency.  It's been 3 days since I can access my wallet and I don't understand any of the instructions on how to "fix" this issue 

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...INFO [08-19|16:04:09] Starting peer-to-peer node instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [08-19|16:04:09] Allocated cache and file handles database=/Users/robertriva/Library/Ethereum/geth/chaindata cache=1024 handles=1024

**Comment by rivaderci88** [comment]
HELLOOO????????

**Comment by debris** [comment]
I believe it's a wrong repo to report the issue. You should reopen it in `go-ethereum` repo: https://github.com/ethereum/go-ethereum/issues

**Comment by Scorpion2185** [comment]
I see you offer on this post https://github.com/ethereum/mist/issues/2426
I had the same problem, go to C:\Users\yourusername\AppData\Roaming\Ethereum\geth (or where is your chaindata folder) and delete, rename or move the chaindata folder. I rename it chaindata- backup. Now the wallet will start and it have to synchronize again everything. Then if it will be stuck in the latest blocks change the internet time to "time.nist.gov". Control panel--> Clock,Language...--> Date and time--> Internet time. And use the option in the wallet-->development light client.
