### ISSUE TITLE
Add an example of data encoding a function without parameter lists

### ISSUE THREAD

**Issue by gogit** [ethereum/wiki#464]
Example of source, signature and abi is given below.

------------------
source example declaration
-----------------
    uint256 public constant minContribution     = 1000000000000000000;

------------------
signature
-----------------

aaffadf3: minContribution()

------------------
abi 
------------------

{
	"constant": true,
	"inputs": [],
	"name": "minContribution",
	"outputs": [{
		"name": "",
		"type": "uint256"
	}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}

**Comment by debris** [comment]
signature of function `minContribution()` is `affadf3`

signature is calculated like this:

```rust
let signature = keccak("minContribution()")[0..4];
```

if `minContribution` was taking some input params eg, `uint256` and `bool`, we would calculate it's signature differently

```rust
let signature = keccak("minContribution(uint256,bool)")[0..4];
```

There is a rust library called [ethabi](https://github.com/paritytech/ethabi) which also provides easy to use command line user interface for encoding abi calls.

**Comment by gogit** [comment]
I've been using the RPC call "eth_call", so adding the encoded method signature as "data" : "0xaaffadf3", the result comes back as "0x" and not the hex value defined in the source i.e.

uint256 public constant minContribution     = 1000000000000000000;

Sample request and response from geth node is given below

RPC call to function minContribution()

{
  "jsonrpc" : "2.0",
  "id" : "165573751464696",
  "method" : "eth_call",
  "params" : [ {
    "data" : "0xaaffadf3",
    "gas" : "0x6d7c0",
    "to" : "0x564f14cd798195167ebd44bb71e471fc9333d25b"
  }, "latest" ]
}

RPC json response

{
  "jsonrpc" : "2.0",
  "id" : "165573751464696",
  "result" : "0x"
}

**Comment by gogit** [comment]
I stripped the sol file to the most basic form and it seems to be working

**Source**

pragma solidity ^0.4.16;

contract Hello1 {

    uint256 public constant minContribution     = 1000000000000000000;
            
}

**RPC request**


{
  "jsonrpc" : "2.0",
  "id" : "173023992797677",
  "method" : "eth_call",
  "params" : [ {
    "data" : "0xaaffadf3",
    "to" : "0xa0bba65ae26638ec1cd4cc8091cbbd4bf5e0a271"
  }, "latest" ]
}

**RPC response**

{
  "jsonrpc" : "2.0",
  "id" : "173023992797677",
  "result" : "0x0000000000000000000000000000000000000000000000000de0b6b3a7640000"
}
