### ISSUE TITLE
Web3 library 5.4.2 and the existing documentation not working

### ISSUE THREAD

**Issue by designium** [ethereum/wiki#478]
I'm trying out the API calls as stated from the Web3 page and they are not working as expected. Not sure why. 

I'm running:
- web3 version 5.4.2
- node version 8.6.0

In the web3 page, we have commands like:

web3.version.api
web3.isConnected();

And they are delivering undefined or isConnected is not a function. I'm using testrpc. What is happening?

Here is what I ran:

```javascript
var Web3 = require('web3');
var Eth = require('ethereum.js');

var Web3 = require('web3');
var web3 = new Web3();
```

```javascript
web3.setProvider(new web3.providers.HttpProvider("http://localhost:8545"));
```
    true

```javascript
var version = web3.version.api;
```

```javascript
console.log(version);
```

    undefined

```javascript
var nodeVersion = web3.version.node;
```

```javascript
var print = function (str) {
    console.log(str)
};
```

```javascript
print(web3.version);
```

    1.0.0-beta.22

```javascript
var balance = web3.eth.getBalance('0x398e42da3254a22e13abdbb4c68998bcdb3e2f1d')

```

```javascript
print(balance);
```
    Promise {
      _bitField: 33554432,
      _fulfillmentHandler0: undefined,
      _rejectionHandler0: '100000000000000000000',
      _promise0: undefined,
      _receiver0: undefined }

```javascript
web3.isConnected();
```

    evalmachine.<anonymous>:1
    web3.isConnected();
         ^  

    TypeError: web3.isConnected is not a function
        at evalmachine.<anonymous>:1:6
        at ContextifyScript.Script.runInThisContext (vm.js:50:33)
        at Object.runInThisContext (vm.js:139:38)
        at run ([eval]:775:15)
        at onRunRequest ([eval]:620:18)
        at onMessage ([eval]:588:13)
        at emitTwo (events.js:125:13)
        at process.emit (events.js:213:7)
        at emit (internal/child_process.js:774:12)
        at _combinedTickCallback (internal/process/next_tick.js:141:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by shuxycrypto** [comment]
Any updates on this issue? I'm having the same problems, and stuff like web3.eth.blockNumber returns undefined for me.

**Comment by designium** [comment]
Hi Shuxycrypto, 

There is a huge lag between the actual production library versus the documentations. 

Most of the variables to fetch version data, accounts, etc. are not working at this point. You can try yourself. 

The only way to work is to create the methods that are mostly present and then you create a variable to host the results of the methods using async/await or then. That's the only way I figure things out. No one is updating the documentation at this point. [I'm not the dev btw just user]

**Comment by Amitdangwal007** [comment]
Any updates for this issue??

**Comment by jamesray1** [comment]
You can update the docs yourself they are wikis. Also you can post an issue in https://github.com/ethereum/web3.js.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
