### ISSUE TITLE
File not found or accessible: version.json.js <Aurelia CLI/Windows 10>

### ISSUE THREAD

**Issue by martijndoornik** [ethereum/wiki#480]
Been trying to get web3 to work for a couple of days now, posting it here. 

I can't run web3 properly, because it seems to be missing files, but it looks like the files are not referred to properly or dependencies aren't included with the installation of web3. I can't find any additional information on installing web3. The process I do to install is:

`npm install --save web3` (tried "web3", "web3@0.20.0" and "web3@1.0.0-beta.20", but the latter failed on installation)
Added the following to "aurelia.json" file: 

`{
            "name": "web3",
            "path": "../node_modules/web3",
            "main": "index"
          }`

When running the app, I get the following messages in console:
![image](https://user-images.githubusercontent.com/3370256/31380427-a1df91cc-adb1-11e7-9201-c8558a8507d8.png)

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
