### ISSUE TITLE
why change to web3.eth.getAccounts(console.log);

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/wiki#481]
Old way to get accounts is `web3.eth.accounts` why change it to web3.eth.getAccounts(console.log)?
where can I see the change logs?

**Comment by Moejoe90** [comment]
This is just an asynchronous way for getting accounts. Nothing changed. This function generates a `Promise`  you have to resolve the promise first by either using `.then` or `await`  
Where did you get this from?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed, although the issue seems to have been resolved.
