### ISSUE TITLE
Cannot import wallet JSON from Parity onto Mist

### ISSUE THREAD

**Issue by sleepndevelop** [ethereum/wiki#484]
I have exported my Parity wallet , i have then installed Mist, then it asked me "Use Ethereum Main Net" or "Use Testnet" and i chose Main Net,  and then  it asked me to import a wallet.
So i have dropped there my JSON file just exported from Parity.

But the Mist process crashed instantly.
Why?

**Comment by jamesray1** [comment]
This is not an issue with the Wiki, please post an issue in Mist. https://github.com/ethereum/mist

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed. Also links to Parity to ask them for help as well.
