### ISSUE TITLE
Subtilties document is outdated

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/wiki#49]
https://github.com/ethereum/wiki/wiki/Subtleties

It says:
> If a transaction triggers an exception, then:
>
>    The value transfer from sender to recipient still takes place

and

> If a CALL operation's sub-execution triggers an exception, then:
>      Ether value is still sent

According to @chriseth this has not been correct since before frontier.

**Comment by chriseth** [comment]
Added a disclaimer at the beginning.

**Comment by drupalnomad** [comment]
Thanks!
