### ISSUE TITLE
Deleted Sharding-FAQ

### ISSUE THREAD

**Issue by josephjohnston** [ethereum/wiki#490]
I'm so sorry, but I've accidentally deleted your Sharding-FAQ page. I am a naive new user of github. I just assumed any modification of the page would have to be approved in a pull request, or I'd have to be added as a collaborator. Have I in fact deleted it? I hope someone can use their local repo to restore that wiki...

**Comment by boatnoy** [comment]
I've clipped it in my Evernote here
https://www.evernote.com/shard/s1/sh/44b00155-9598-4f62-80b5-2071e8d314b4/1d19ca36b6842d8c213bc43c8abc8314

**Comment by jonchoi** [comment]
Does someone have a local copy of the latest wiki commits? Then it can be pushed back to the repo.

[Instructions via stackoverflow](https://stackoverflow.com/questions/24797429/how-do-i-undo-deleting-a-github-wiki-page)

```
git clone https://myusername@github.com/myusername/foobar.wiki.git
git checkout $(git rev-list -n 1 HEAD -- yourPage)^ -- yourPage
```

Looks like @janx and @Leo-Mu had some recent commits?

**Comment by jonchoi** [comment]
@vbuterin just restored. 

https://github.com/ethereum/wiki/wiki/Sharding-FAQ/_history

Someone should go ahead and close the issue.

**Comment by josephjohnston** [comment]
Thank you for your help!
