### ISSUE TITLE
Improve the Wiki

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/wiki#5]
The github wiki can actually serve as a decent wiki if we improve it a bit for better accessibility.
- create a proper start page, which
  - gives orientation
  - invites user to edit
  - links the github wiki help pages
  - explains how to check out the wiki locally
- cleanup the sidebar to list english pages only 
- use the footer to link other languages
- interlink wiki pages where appropriate
- promote the wiki by linking it from ethereum.org

**Comment by leonklingele** [comment]
Also please make sure images in the wiki are properly displayed and don't yield 404 :)
https://github.com/ethereum/wiki/wiki/White-Paper#bitcoin-as-a-state-transition-system

**Comment by jamesray1** [comment]
Myself and others have already done a lot of this work. I did make a [PR to add a link to ethereum.org](https://github.com/ethereum/ethereum-org/pull/794), which has been merged, but it isn't visible yet. Note also that the website is being redesigned with https://github.com/ethereum/ethereum-org-website.

**Comment by jamesray1** [comment]
However I'm going to reopen this as not all of this has been done yet.

**Comment by jamesray1** [comment]
OK that's partially done, but completed with https://github.com/ethereum/wiki/wiki#contribution-guidelines.

**Comment by jamesray1** [comment]
I believe all issues have now been addressed, except perhaps for the website wiki, which has been attempted but hasn't been resolved. I have opened a separate issue for that: #603.
