### ISSUE TITLE
Mix Ide freezing on startup

### ISSUE THREAD

**Issue by RTDoggy** [ethereum/wiki#50]
WARNING: This project is using the experimental QML API extensions for QtWebEngi
ne and is therefore tied to a specific QtWebEngine release.
WARNING: The experimental API will change from version to version, or even be re
moved. You have been warned!

QtWebEngineProcess not found at location C:/Program Files/Ethereum/bin\QtWebEngi
neProcess.exe. Trying fallback path...
Layout must be attached to Item elements
Layout must be attached to Item elements
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
qrc:/QtQuick/Controls/ScrollView.qml:232:9: QML Binding: Binding loop detected f
or property "value"
qrc:/QtQuick/Controls/ScrollView.qml:225:9: QML Binding: Binding loop detected f
or property "value"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "pr
eferredWidth"
  i  00:16:19.705|main  Killing blockchain & extras database (WithExisting::Kill
).
  i  00:16:19.705|main  Killing state database (WithExisting::Kill).
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
  i  00:16:19.751|main  Killing blockchain & extras database (WithExisting::Kill
).
  i  00:16:19.751|main  Killing state database (WithExisting::Kill).
  i  00:16:19.783|main  Killing blockchain & extras database (WithExisting::Kill
).
  i  00:16:19.798|main  Killing state database (WithExisting::Kill).
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined
] to bool
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined
] to bool
qrc:/QtQuick/Controls/TextArea.qml:728:24: Unable to assign [undefined] to QColo
r
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot rea
d property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot rea
d property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:72:42: Unable to assign T
extArea_QMLTYPE_172 to TextField_QMLTYPE_97
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read propert
y of null
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read propert
y of null
qml: Unable to initiate request to the live network. Please verify your ethereum
 node is up. Error status: 0
qml:
qml: Unable to initiate request to the live network. Please verify your ethereum
 node is up. Error status: 0
qml:
qml: Unable to initiate request to the live network. Please verify your ethereum
 node is up. Error status: 0
qml:
qml: Unable to initiate request to the live network. Please verify your ethereum
 node is up. Error status: 0
qml:
qml: Unable to initiate request to the live network. Please verify your ethereum
 node is up. Error status: 0
qml:
qml: Closing project
qml: Creating project dfg at file://C:/Users/admin/Desktop
qml: Closing project
qml: Loading project at file://C:/Users/admin/Desktop/dfg
  i  00:16:44.007|main  Killing blockchain & extras database (WithExisting::Kill
).
  i  00:16:44.016|main  Killing state database (WithExisting::Kill).
Waiting for current execution to complete
  i  00:16:45.088|<unknown>  Decreasing DB node ref count below zero with no DB
node. Probably have a corrupt Trie. #84acdce9ÔÇª
  i  00:16:45.104|<unknown>  Decreasing DB node ref count below zero with no DB
node. Probably have a corrupt Trie. #a71b164eÔÇª

**Comment by salsa-dev** [comment]
Hi, this issue should be reported here https://github.com/ethereum/mix/issues
