### ISSUE TITLE
the white paper is gone

### ISSUE THREAD

**Issue by cliffxuan** [ethereum/wiki#513]
The Ethereum Whitepaper link on the wiki homepage https://github.com/ethereum/wiki/wiki points to this url:

https://github.com/ethereum/wiki/wiki/White-Paper

 it doesn't actually exists. When you click it, a "Create new page" is displayed.

![screen shot 2018-01-02 at 1 43 11 pm](https://user-images.githubusercontent.com/640204/34485504-f2cb3d36-efc2-11e7-959d-2326bfe1509d.png)

**Comment by cgopalan** [comment]
The page is there in the code ( https://github.com/ethereum/wiki/blob/master/pages/white-paper/%5Benglish%5D-white-paper.md ), but somehow the link is broken.

**Comment by cliffxuan** [comment]
Some of the images on that link don't work.

**Comment by luoc0815** [comment]
Okay, it looks like user @TreBlack broke the page as you can see [here](https://github.com/ethereum/wiki/wiki/White-Paper/_history).

**Comment by whispers16** [comment]
do anyone may restore the broke images?

**Comment by cgopalan** [comment]
@whispers16 Yes, I have fixed it and opened a PR for that here: https://github.com/ethereum/wiki/pull/515

**Comment by jamesray1** [comment]
See https://github.com/ethereum/wiki/wiki/White-Paper for the latest and https://github.com/ethereum/wiki/blob/old-before-deleting-all-files-go-to-wiki-wiki-instead/old-whitepaper-for-historical-reference.md#historical-sources-of-the-white-paper for history.
