### ISSUE TITLE
Missing white paper

### ISSUE THREAD

**Issue by fokot** [ethereum/wiki#518]
Nothing is here https://github.com/ethereum/wiki/wiki/White-Paper
But it can still be found on webarchive https://web.archive.org/web/20180106225455/https://github.com/ethereum/wiki/wiki/White-Paper

**Comment by edwickable** [comment]
thanks for the link to the archive!

**Comment by fokot** [comment]
There are also revisions. Someone renamed the file so I fixed the link from
- [Ethereum Whitepaper](https://github.com/ethereum/wiki/wiki/White-Paper)
to
- [Ethereum Whitepaper](https://github.com/ethereum/wiki/wiki/Ethereum-White-Paper)

**Comment by jamesray1** [comment]
This also occurred with #526.
