### ISSUE TITLE
Mix "Edit Starting Parameters" not working properly

### ISSUE THREAD

**Issue by pietdion** [ethereum/wiki#54]
Adding user accounts does not work properly.   After saving and then returning "shuffles" the account information.    Perhaps it is because I define/use the same account information inside the solidity contract?

**Comment by LianaHus** [comment]
I can't reproduce the issue. could you please add some details: what exactly you are doing with account information in the contract?

**Comment by pietdion** [comment]
Here is a sequence of steps that seems to reproduce the error on my machine (Mac OSX)

1.   Start a new project
2.   Genesis Block > Edit Starting parameters
3.   Delete or copy address of one of the Accounts   (This may cause Mix to crash — not always)
4.   Rename one of the accounts
5.   Click OK 
6.   Genesis Block > Edit Starting parameters
7.   Click OK
8.   Genesis Block > Edit Starting parameters

… Maybe copy address or similar.   At this stage contradictory information starts appearing in the user accounts  (Duplicate accounts, some accounts missing etc etc).   Every time I Edit starting parameters slightly different information appears and some accounts are dropped, to reappear perhaps on a later “Edit starting parameters”.   So never sure which is the right state of affairs.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
