### ISSUE TITLE
Remove "-" of repository description

### ISSUE THREAD

**Issue by zaq1tomo** [ethereum/wiki#544]
I'd like you to revise the description of this repository because "-" included when I look at the list of repositories.

**Comment by jamesray1** [comment]
I believe this requires someone with higher edit permissions, e.g. @Souptacular.

**Comment by jamesray1** [comment]
![screenshot from 2018-05-31 15-13-46](https://user-images.githubusercontent.com/16969914/40762734-4314aa7e-64e5-11e8-8dd1-1989b1d2d49b.png)

**Comment by Souptacular** [comment]
Fixed!

**Comment by Platinumwrist** [comment]
Your help is extraordinary
