### ISSUE TITLE
Where's skype channel/WS_Secret?

### ISSUE THREAD

**Issue by ZeroDeth** [ethereum/wiki#55]
Hi

can't join/find a channel of skype? where's WS_Secret?

**Comment by goodc0re** [comment]
skype is also giving me the message "can't join .."  where do I get the WS_SECRET?

**Comment by bobsummerwill** [comment]
We don't really use Skype much any more.    Most of the conversation happens on Gitter.

Links below:

http://www.ethdocs.org/en/latest/introduction/community.html
