### ISSUE TITLE
mining guide for beginners?

### ISSUE THREAD

**Issue by ghost** [ethereum/wiki#555]
I would like to start mining.
so two questions:
1. is it still a good idea to start now or will eth mining be abolished very soon and thus becomes unprofitable very soon?

2. Do you have a recommendation for a good mining guide for beginners?

**Comment by grml123** [comment]
well nobody know when exactly mining will be over. Dont buy overpriced new cards. But maybe if you have some spare cards. I know a big maybe. Or get them for normals prices (which is unlikely) or you see it as a hobby you might wanna check it out. it is a lot of fun.

a very good guide that has helped me a lot was this one:

http://ether-mining.info/

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
