### ISSUE TITLE
Design Rationale: Is the description of a stack size limit correct?

### ISSUE THREAD

**Issue by takenobu-hs** [ethereum/wiki#559]
In ["Design Rational"][1], it is stated that `Not having a stack size limit` as follows.

> Not having a stack size limit - no particular justification either way; note that limits are not strictly necessary in many cases as the combination of gas costs and a block-level gas limit will always act as a ceiling on the consumption of every resource.

However, [yellowpaper][2] and [geth implementation][3] states that the data stack size is limited to 1024.

Does the description of "Design Rational" outdated?
Or, does "Design Rational" describe future specifications?

Please see also [related discussion][4].

[1]: https://github.com/ethereum/wiki/wiki/Design-Rationale#virtual-machine
[2]: https://ethereum.github.io/yellowpaper/paper.pdf#page=11
[3]: https://github.com/ethereum/go-ethereum/blob/master/params/protocol_params.go#L56
[4]: https://github.com/takenobu-hs/ethereum-evm-illustrated/issues/1

**Comment by jamesray1** [comment]
I'm pretty sure 1024 is correct as the stack size limit, this has been edited with https://github.com/ethereum/wiki/wiki/Design-Rationale/e17115948eca8d04c3982ed6965ac821a40e798d.

**Comment by jamesray1** [comment]
Note also: Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.

**Comment by jamesray1** [comment]
@pirapira

**Comment by takenobu-hs** [comment]
Thank you very much for the explanation.
