### ISSUE TITLE
 format of deployment.js 

### ISSUE THREAD

**Issue by josojo** [ethereum/wiki#56]
Hi,

when I am deploying my contracts, in the deployment.js, there are many line breaks missing.
it would definitively help, if we could get a line break between these pieces:
ctrAddresses["Contract1"].push("0x816328ca6d022cc526ca815e51247715c2fa333b") contracts["Contract2"] = {....

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
