### ISSUE TITLE
The app does not show my created currency

### ISSUE THREAD

**Issue by RogierKonings** [ethereum/wiki#57]
Hi folks,

I would like to display my own crypto currency with this app. I created the currency contract with the desktop ethereum app and transferred this to my other accounts. In the webapp, I can however NOT see the currency on the accounts, even though I am specifically watching this coin. 
Strangely enough, I do see the transactions in bottom, but not the balance...

How is this possible?

Does someone know what's going on?

kind regards

**Comment by alexvandesande** [comment]
This might be related to https://github.com/ethereum/meteor-dapp-wallet/issues/149

Also, this is the wrong place, as this is the ethereum wiki, not the mist/wallet page.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
