### ISSUE TITLE
Error in the Proof of Stake FAQ wiki

### ISSUE THREAD

**Issue by wimel** [ethereum/wiki#579]
In the Proof of Stake FAQ, the Ethereum link [(_this_)](https://github.com/ethereum/wiki/wiki/Proof-of-Stake-FAQ#will-exchanges-in-proof-of-stake-pose-a-similar-centralization-risk-to-pools-in-proof-of-work) is broken, could it be replaced by [(_this_)](https://etherscan.io/stat/miner?range=7&blocktype=blocks) other?

**Comment by jamesray1** [comment]
I see that this has been fixed in the wiki/wiki.
