### ISSUE TITLE
Error installing Mix IDE

### ISSUE THREAD

**Issue by ksank1976** [ethereum/wiki#58]
I am getting the below error when trying to install the Mix IDE for Ethereum.
 "No Such file or Directory". Appreciate your help in resolving the error.

When you exit this IRB session, execution will continue.
irb(/usr/local/Cellar/cpp-ethereum/1.2.3):001:0> exit
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
Errno::ENOENT: No such file or directory - (mix/Mix.app, /usr/local/Cellar/cpp-ethereum/1.2.3/Mix.app)
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Library/Homebrew/extend/pathname.rb:106:in `install_p'
/usr/local/Library/Homebrew/extend/pathname.rb:84:in `block in install'
/usr/local/Library/Homebrew/extend/pathname.rb:65:in `each'
/usr/local/Library/Homebrew/extend/pathname.rb:65:in `install'
/usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb:83:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:130:in `block in install'
/usr/local/Library/Homebrew/formula.rb:930:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1550:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:92:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:36:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:171:in `stage'
/usr/local/Library/Homebrew/formula.rb:1540:in `stage'
/usr/local/Library/Homebrew/formula.rb:926:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:

**Comment by bobsummerwill** [comment]
Please could you re-file this against http://github.com/ethereum/mix?
This issue tracker is for the Ethereum Wiki.   Thanks!

PS.  Also best to put the logs into a gist.github.com file and link, so the formatting doesn't go weird.
