### ISSUE TITLE
Documentation for eth_getTransactionByHash must specify direction of search as txid is not unique

### ISSUE THREAD

**Issue by paulvi** [ethereum/wiki#580]
As in general case (when blockchain is running over very long time or because of bugs like https://github.com/ethereum/go-ethereum/issues/1408)  
transaction hash aka `txid` is not unique within blockchain instance (i.e. 2 and more transactions with the same hash are possible),
the [Documentation for eth_getTransactionByHash](
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash) should specify whether search is done from end of blockchain or from the block 0.

Otherwise different implementations may have had different approaches done, and this innocently looking API `eth_getTransactionByHash`  will give different results in different implementations (e.g. geth vs Parity vs cpp-ethereum etc )

Once it is stated in main wiki, it would be bug, if implemented otherwise.

**Comment by karalabe** [comment]
You are referencing a bug fixed 3 years ago. Transactions id's are unique, period.

**Comment by paulvi** [comment]
Well, in general case (not recalling about older bugs) it is possible, that 2 absolutely different transaction will get the same hash. It is just probability of this  (when using 256bit value for hash) is extremely small.

Peter @karalabe , would you agree for general case?

Then let's assume about 1 000 000 transactions this year and later, 1 000 000 000 = 10^9 tr per year is still much smaller than 2^256=10^19 of all possible values, but there is always a chance that collision.

**Comment by karalabe** [comment]
If you can get the same hash for two transactions, then you can get the same hash for different blocks, or the same hash for different state tries, or the same private key for different accounts. TL;DR At that point, Ethereum is broken.

**Comment by paulvi** [comment]
I bet nobody can get the same hash on purpose.  
However 2^256 is still limited number and given enough time and some bad/good luck, some collision is possible. In theory. 
In practice it is likely to take 10^3..10^9 years, but in my code I would check again whether timestamp in used within hash function call. (I just don't know where it is in geth code...)

I cannot tell about other implementations, but Ithink it is more proper to start searching from the end, as it is more likely that some transaction one searching would be within the latest, then within something 5-10-20 years old.
