### ISSUE TITLE
Is the result of getBlockByNumber final?

### ISSUE THREAD

**Issue by yuluyi** [ethereum/wiki#601]
Will the result of getBlockByNumber change due to the longest chain issue?

Say, I called getBlockByNumber(100000) now and got block A. 10 mins later, it turns out block A is not in the longest chain. Will the result of getBlockByNumber(100000) change then?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
