### ISSUE TITLE
Update NatSpec examples for consistency

### ISSUE THREAD

**Issue by fulldecent** [ethereum/wiki#604]
Regarding file https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format

That natspec spec doesn't really specify whether or not periods are required or not, including giving multiple contradictory examples and unspecified multiline specifications

```
/// @notice (balanceInmGAV / 1000).fixed(0,3) GAV is the total funds available to who.address().
```

Also in this spec document are

```
/// @notice Enable or disable approval for a third party ("operator") to manage
/// all of msg.sender's assets.
```

and

```
/// @notice A distinct Uniform Resource Identifier (URI) for a given asset.
```

along with inconsistent periods at the end of @param tags like

```
/// @param _operator Address to add to the set of authorized operators.
```

We want the rule: "no trailing periods except on @dev tags".

# Work plan

- [ ] State this rule
- [ ] Update examples in the wiki to follow that rule

---

Credit to @shrugs at https://github.com/ethereum/EIPs/pull/1151#issuecomment-397123061

---

Discussion: I support this change because I expect that the `notice` and `param` tags will be shown in MetaMask one day. Just imagining how the user interface might look, it will be a form with a name, the value, and a descriptor text for each field. I think in general you don't need a period. Here is how it might look.

![screen shot 2018-06-16 at 6 12 58 pm](https://user-images.githubusercontent.com/382183/41502826-f8547876-7190-11e8-9c0e-ebaafb1733d5.png)

**Comment by jamesray1** [comment]
I think if the notice is a complete sentence it can have a period but generally these descriptions are not complete sentences, and rewriting them like that makes them more verbose when it is obvious what they are referring to. E.g. "Address to add to the set of authorized operators." could be rewritten to "address to add to the set of authorized operators" or, "This is the address to add to the set of authorized operators." The latter is more verbose, and while more grammatically correct, isn't necessary when it is obvious what the description is referring to.

**Comment by jamesray1** [comment]
Maybe try to contact some NatSpec implementers and reach a consensus with them.
