### ISSUE TITLE
I think there is a typo in a graph of Development Guide 

### ISSUE THREAD

**Issue by tjsbzc** [ethereum/wiki#608]
Hi Ethereum Team,

I think there are typos in 2 graphs the Wiki : [.](url)https://github.com/ethereum/wiki/wiki/Ethereum-Development-Tutorial The "EOA" are missed by typo "EAO"

here is the original pictures: 

![img](https://raw.githubusercontent.com/ethereumbuilders/GitBook/master/en/vitalik-diagrams/contract_relationship.png)

and 

![img](https://raw.githubusercontent.com/ethereumbuilders/GitBook/master/en/vitalik-diagrams/contract_relationship2.png?1)

Here are my corrections. 

![contract_relationship2_2ben](https://user-images.githubusercontent.com/23174036/42495679-574aa7c4-8456-11e8-90f2-be77ad5ad135.png)

![contract_relationship_2ben](https://user-images.githubusercontent.com/23174036/42495688-5c79d936-8456-11e8-8cc6-20a8d907ec38.png)

Thanks,

2Ben

**Comment by jamesray1** [comment]
You have successfully resolved this yourself, good job!
