### ISSUE TITLE
Web3js API docs are wonky

### ISSUE THREAD

**Issue by Heph789** [ethereum/wiki#609]
The links are not working along with other things.

**Comment by songyuanjie** [comment]
what's something happen, the docs  are monky!

**Comment by jamesray1** [comment]
Please file this issue with the web3 team. See also https://github.com/ethereum/wiki/wiki#issues-and-pull-requests.

**Comment by jamesray1** [comment]
I'll leave this open as a general issue for web3, allow personally I don't have time to handle them, nor do others seem to.
