### ISSUE TITLE
Exponentiation ** ignores Base and always uses 2

### ISSUE THREAD

**Issue by Frank420** [ethereum/wiki#61]
I want to do this:
`dailyAllowance = _dailyTokens * (10 ^ _nrDecimals)`
1000.0000 = 1000 \* (10 ^ 4)
in order to get the nr we need to remember for daily allowance.

I would expect this to work in Solidity/Mix:
`dailyAllowance = _dailyToken * (10 ** _nrDecimals)`

However, it always returns this:
`dailyAllowance = _dailyToken * (2 ^ _nrDecimals)`
= 16.000

Is that a bug? Does *\* not do what I expect it to?
`**: base ^ exponentiation`

I am now using a workaround
`
dailyAllowance = _dailyAllowance;
for (uint i = 0; i < _myTokenDecimals; i++) {
dailyAllowance *= 10;
}`

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
