### ISSUE TITLE
Ubuntu 18.04 LTS, can not install Web3

### ISSUE THREAD

**Issue by wangsh-nj** [ethereum/wiki#610]
I am using the Ubuntu 18.04 LTS, I can not install Web3 successfully with below error:

wangsh@wangsh-linux:~$ sudo npm install web3
[sudo] password for wangsh:
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: â ï¸  WARNING â ï¸ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit  git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible resetting remote /home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e because of error: { Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm ERR! git clone --template=/home/wangsh/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: Cloning into bare repository '/home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e'...
npm ERR! git clone --template=/home/wangsh/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/wangsh/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[0: 192.30.255.112]: errno=Connection timed out
npm ERR! git clone --template=/home/wangsh/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[1: 192.30.255.113]: errno=Connection timed out
npm ERR! Linux 4.15.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "web3"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/wangsh/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e
npm ERR! Cloning into bare repository '/home/wangsh/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.255.112]: errno=Connection timed out
npm ERR! github.com[1: 192.30.255.113]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wangsh/npm-debug.log

**Comment by jamesray1** [comment]
This is not a wiki issue.
