### ISSUE TITLE
shouldn't you remove sendRawTransaction for sendSignedTransaction?

### ISSUE THREAD

**Issue by lebed2045** [ethereum/wiki#611]
all new versions, supposedly since supposedly 2016 uses sendSignedTransaction function so we should use `web3.eth.sendRawTransaction || web3.eth.sendSignedTransaction;` to make it work locally and on heroku. Same with `let toHexF = web3.toHex || web3.utils.toHex;` which is inconvenient to say at least. If the documentation will have actual information and explanation what happened in which version - would be better.

**Comment by songyuanjie** [comment]
sendSignedTransaction is great，it can be understood literally

**Comment by lebed2045** [comment]
@songyuanjie I do agree, however, the fact that web3@0.2.x and web3@1.x have different interface can be emphasized more clear on the documentation. For example, put in the title like web3@0.2 Latest stable Version.

**Comment by jamesray1** [comment]
See https://github.com/ethereum/wiki/wiki#issues-and-pull-requests, file an issue in the web3 repo.
