### ISSUE TITLE
Percentage Contradiction on GHOST Description

### ISSUE THREAD

**Issue by houruomu** [ethereum/wiki#613]
Link:[https://github.com/ethereum/wiki/wiki/White-Paper#modified-ghost-implementation](url)
In which, it first states:

> a stale block receives 87.5% of its base reward, and the nephew that includes the stale block receives the remaining 12.5%. Transaction fees, however, are not awarded to uncles.

But on a later paragraph, it states: 

> For every uncle U in block B, the miner of B gets an additional 3.125% added to its coinbase reward and the miner of U gets 93.75% of a standard coinbase reward.

Is this a contradiction?

**Comment by ChrisChinchilla** [comment]
@houruomu as @jamesray1 states above, please recreate this issue using the template, and even better, if you have a proposed fix, let me know what you think the change should be and I'd be happy to apply them.
