### ISSUE TITLE
ABI spec question: fixed-size zero-length arrays (`<type>[0]`)

### ISSUE THREAD

**Issue by Qqwy** [ethereum/wiki#614]
In the ABI spec section [Types](https://solidity.readthedocs.io/en/develop/abi-spec.html#types), the following statement is written:

>  <type>[M]: a fixed-length array of M elements, M >= 0, of the given type.

In the section [Formal specification of encoding](https://solidity.readthedocs.io/en/develop/abi-spec.html#formal-specification-of-the-encoding), the following statement is written:

> T[k] for any dynamic T and any k >= 0

Does that mean that we can have an array (of either static or dynamic elements) with fixed size, where this fixed size is `0`? (so the _type_ `int256[0]`, or `bool[0]`, or `string[0]`, or `bytes[][][][][0][]`?)
I can understand the need for supporting a zero-tuple (it is very common from functional languages), but I do not understand what a fixed-size zero-length array is supposed to be for.

Do they exist, or is this an off-by-one error in the documentation?
If they do exist, are these encoded as 'empty arguments' that do not take up any space in the hexadecimal ABI string?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/blob/master/ISSUE_TEMPLATE.md.
