### ISSUE TITLE
wiki - getBlockByHash result typo

### ISSUE THREAD

**Issue by ilanolkies** [ethereum/wiki#615]
In wiki, getBlockByHash detail:
```javascript
"jsonrpc":"2.0",
"result": {p
    "number": "0x1b4", // 436
```
Letter p wrong

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/blob/master/ISSUE_TEMPLATE.md.

**Comment by jamesray1** [comment]
You can fix this yourself.
