### ISSUE TITLE
Examples from the main docs on your website are mostly deprecated due to the constructor (...) (...) error

### ISSUE THREAD

**Issue by MindfulMe** [ethereum/wiki#617]
The function: 
```
    function MyToken(uint256 initialSupply) public {
        balanceOf[msg.sender] = initialSupply;
    }
```
gives the following error:
 `Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.`

Solution: considered replace the example function in the documentation with the constructor method

**Comment by MindfulMe** [comment]
Plus your Ethereum wallet takes to much processing power while running. Platform: MacOS.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/blob/master/ISSUE_TEMPLATE.md.
