### ISSUE TITLE
[wiki] Ethash visualization

### ISSUE THREAD

**Issue by lookfirst** [ethereum/wiki#618]
I ran across this visualization that someone did:

https://docs.google.com/drawings/d/12yaGlsb5cz7IlWXcwgT6xXympFDVf84C6UrYkqHRipQ/edit

Also explained here:

https://www.vijaypradeep.com/blog/2017-04-28-ethereums-memory-hardness-explained/

It seems like adding the diagram to [this page](https://github.com/ethereum/wiki/wiki/Ethash), would make sense, but I am not sure of its correctness. That said, the general idea of the diagram really helped me visualize things far better than a bunch of code on the page.

Opening this issue for discussion for adding it. Thanks.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/blob/master/ISSUE_TEMPLATE.md.
