### ISSUE TITLE
[wiki] Error in Proof Of Stake FAQ (wrong EV calculation)

### ISSUE THREAD

**Issue by ymsaid** [ethereum/wiki#619]
In the `nothing at stake problem` section of the FAQ, there is an example explaining the consequences of a strategy punishing the validator for validating the wrong chain. In the diagram here https://github.com/vbuterin/diagrams/blob/master/slasher2sec.png
the EV of  only voting for A is shown as `EV = 0.9` when it should be `EV = 0.9 - 0.1*5 = 0.4`. Basically if chain A has a `p=0.9` chance of being the correct at the time of making the decision, the state of the world where B is the right decision (`p=0.1`) must be taken into account.

This is an important detail, because it shows why the penalty cannot exceed a certain limit relative to reward without breaking the `participation constraint` (every validator is better off not validating any chain). This discussion should probably be added to the associated paragraph.

In the particular example of the paragraph, the maximum penalty is `9`. After that point, even choosing the most likely chain is not worth the trouble (`EV <=0`). More generally, an increase in the level of confusion in the network (measured by the number of concurrent chains) combined with a large penalty risks halting all validations.

cc @vbuterin

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/blob/master/ISSUE_TEMPLATE.md.

**Comment by gin** [comment]
**Question about PR process:**
When updating the diagram for this issue, should the PR be on https://github.com/vbuterin/diagrams/
or
should the PR be on this repository (https://github.com/ethereum/wiki.wiki.git) where the updated diagram is pushed to here (with the link updated in the Markdown)?

**Comment by ChrisChinchilla** [comment]
@gin Good question! I'd say, attach a copy of the image to your PR and we'll figure out where to move it to.

**Comment by hjlee9182** [comment]
@gin https://github.com/ethereum/wiki.wiki.git
This address was 404 Found, Is it right?

**Comment by ChrisChinchilla** [comment]
Err, assuming you are tackling this issue (https://github.com/ethresearch/eth-wiki/issues/19), then PRs should be to the eth-wiki repo, as we're slowly migrating there.

**Comment by ChrisChinchilla** [comment]
This issue is being handled elsewhere
