### ISSUE TITLE
Compiler error checking fails....

### ISSUE THREAD

**Issue by DaveAppleton** [ethereum/wiki#62]
```
    struct bankData {
        uint256 buy;
        uint256 sell;
        uint256 gold;
        uint256 cash;
        address banker;
        address exchangerateDaemon;
        address topupDaemon;
        address goldDaemon;
    }
```

...

```
    modifier MustBeUser(address user, string currency) {
        if (!bankData[user].created) throw;
        if (!bankData[user].currency != currency) throw;

        _
    }
```

crashes the compiler rather than generating an error

```
Internal compiler error during compilation:
/tmp/cpp-ethereum20160118-36398-1afsq9/solidity/libsolidity/analysis/TypeChecker.cpp(51): Throw in function const TypePointer &dev::solidity::TypeChecker::type(const dev::solidity::Expression &) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = Type requested but not present.
```

**Comment by stevenroose** [comment]
Did you manage to fix this?

**Comment by jdetychey** [comment]
Hey,
For what it's worth 1 year after, I had this error and managed to fix it. One of my solidity variable was named with a uppercase letter like so:
```address public Owner```
instead of
```address public owner```
Make sure you have note that hidden somewhere in your code. 
Wild Guess the compiler might misinterprete variables for functions. 
It also happen when you have a lot of comments with ```///``` instead of ```//```

**Comment by stevenroose** [comment]
> It also happen when you have a lot of comments with `///` instead of `//`

Because that makes a lot of sense?

**Comment by DaveAppleton** [comment]
Sorry - only just noticed this. I was forced to move away from that codebase so it has kinda got lost in the mists of time. If I manage to crash the compiler again I will report it.
Meanwhile I will close this.
