### ISSUE TITLE
[Docs] parameter order for web3.eth.sign()

### ISSUE THREAD

**Issue by hudsonburgess** [ethereum/wiki#620]
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsign

The signature is listed as 

> `web3.eth.sign(address, dataToSign [, callback])`

But the example is

```js
var result = web3.eth.sign(
    "0x9dd2c369a187b4e6b9c402f030e50743e619301ea62aa4c0737d4ef7e10a3d49", // first argument is web3.sha3("xyz")
    "0x135a7de83802408321b74c322f8558db1679ac20"); 
```

Which parameter is actually first -- `address` or `dataToSign`?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/blob/master/ISSUE_TEMPLATE.md.

**Comment by ChrisChinchilla** [comment]
Closed in https://github.com/ethresearch/eth-wiki/issues/18
