### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by tucker-chambers** [ethereum/wiki#625]
Sorry if this distracting, but the docs are so good. I found a typo under the documentation for eth_getTransactionReceipt.

Next to `transactionIndex`, it says: integer of the transactions index position in the block.

I think it should the "of the transaction's"

**Comment by RichardLitt** [comment]
Thanks, @tucker-chambers. I've edited it - anyone can edit the Wiki, including you, which is one of the reasons the Wiki is such a powerful resource. In the future, see if you can edit it directly. 

For now, this issue can be closed.

**Comment by tucker-chambers** [comment]
@RichardLitt Will edit directly via the Wiki next time. Thank you.
