### ISSUE TITLE
Poor info about execution Smart Contract setter method

### ISSUE THREAD

**Issue by Lomey** [ethereum/wiki#627]
when I invoke Smart Contract setter method using truffle console it returns a lot of data
![image](https://user-images.githubusercontent.com/16382694/46583789-98914e00-ca64-11e8-81e8-6f3a77aeda81.png)
But when I doing it using Contract class I get only tx id and other info is not useful:

`contract = ::Ethereum::Contract.create(name:    ENV['ETH_SMART_CONTRACT_NAME'],
                                                                     truffle: { paths: [ENV['ETH_SMART_CONTRACT_FOLDER']] },
                                                                     client:  client)`

![image](https://user-images.githubusercontent.com/16382694/46583823-f6be3100-ca64-11e8-9e98-ca4a1ac3beb6.png)

So is it possible to more information?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/blob/master/ISSUE_TEMPLATE.md.
