### ISSUE TITLE
web3.eth.sign and web3.personal.sign

### ISSUE THREAD

**Issue by zmyuanmy** [ethereum/wiki#635]
the result use  web3.personal.sign is defference from web3.eth.sign,
i can ecrecover the result of the  web3.eth.sign,
but I want to give users a friendly hint. i can't ecrecover the result of the  web3.personal.sign.
what shuold i do ?

**Comment by ChrisChinchilla** [comment]
This is more of a question than an issue with the wiki. I'm wrong, then please reopen.
