### ISSUE TITLE
no documentation for eth_signTransaction

### ISSUE THREAD

**Issue by eshaben** [ethereum/wiki#636]
There is a lack of documentation for the `eth_signTransaction` method. I thought it didn't exist until a co-worker pointed out this pull request: https://github.com/ethereum/go-ethereum/pull/1666

**Comment by jeryltimbobolan** [comment]
Any idea on the parameters that will be supplied for this?

**Comment by jeryltimbobolan** [comment]
Any idea on the parameters that will be supplied for this?

**Comment by njgheorghita** [comment]
@jeryltimbobolan They're listed under `eth_signTransaction` [here](https://github.com/bitpshr/EIPs/blob/147609158191a701cf02c8556d5e529ffcb31cd2/EIPS/eip-1474.md)

**Comment by ChrisChinchilla** [comment]
We are slowly trying to move this Wiki to a new wiki, and this issue is fixed there, so closing this.

https://eth.wiki/en/json-rpc#eth_signtransaction
