### ISSUE TITLE
JSON RPC eth_newFilter documentation inadequate

### ISSUE THREAD

**Issue by miohtama** [ethereum/wiki#64]
eth_newFilter documentation here: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
- Should explain the life cycle of a filter: does it exist permanently or the duration of a node process
- Is there a way to list existing filter
- Is there a way to remove filter

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
