### ISSUE TITLE
how can we generate address using passphrase

### ISSUE THREAD

**Issue by anjalialance** [ethereum/wiki#644]
Hi,
I am trying to generate an address from passphrase. The passphrase or mnemonics are generated by bip39. Also, have created the wallet using web3 for ether. The successful transaction has already been performed using web3. Now, I want to extract the address from the passphrase without storing the passphrase and private key in database. Do you have any tutorial or any piece of code how can I perform the above mentioned problem. Kindly help.

**Comment by ChrisChinchilla** [comment]
Not a wiki issue
