### ISSUE TITLE
please suggest me to create a filter to last n number of transactions in parity JSON RPC

### ISSUE THREAD

**Issue by malenchelon** [ethereum/wiki#649]
I Want to get last n number of transactions as like in bitcoin listtransactions. I want that thing to be in a filter so that i can grab them when ever i need using json rpc command

**Comment by ChrisChinchilla** [comment]
As far as I can tell from this - https://github.com/ethereum/go-ethereum/issues/1897

it has been widely discussed, but not implemented.
