### ISSUE TITLE
Token System - N non-positive

### ISSUE THREAD

**Issue by wanneslier** [ethereum/wiki#65]
""More formally, a token system is a database mapping addresses to numbers with the property that the primary allowed operation is a transfer of N tokens from A to B, with the conditions that N is non-negative, N is not greater than A's current balance, and a document authorizing the transfer is digitally signed by A.""
I wonder why N should be positive. To clarify: it looks to me as those that for years thought that interest rates could not be negative - but they can as was proven already by Switzerland in the 80's and many others since then.
So - can anyone clarify me on this?
Thanks!!

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.

It's to prevent an attack, transferring tokens from B to A without B's permission.
