### ISSUE TITLE
Solidity Documentation URL gives 404

### ISSUE THREAD

**Issue by asasidh** [ethereum/wiki#66]
The page https://github.com/ethereum/wiki/wiki/The-Solidity-Programming-Language says that Solidity documentation can be found at http://ethereum.github.io/solidity/

This link gives 404.

**Comment by debris** [comment]
fixed in https://github.com/ethereum/wiki/wiki/The-Solidity-Programming-Language/_compare/7ef6657e4356edafdc521069659d0a1aa550f720
