### ISSUE TITLE
Wrong character escaped in the white paper references

### ISSUE THREAD

**Issue by 29988122** [ethereum/wiki#663]
![圖片](https://user-images.githubusercontent.com/5474709/60038143-0a3e2480-96e6-11e9-9e58-75e2088eb481.png)

The underscore symbol is probably escaped twice, or should not be escaped at all.
wrong: https://en.wikipedia.org/wiki/Zooko's\_triangle
correct: https://en.wikipedia.org/wiki/Zooko's_triangle

Yeah it's a small issue, and eth 2.0 is approaching - still it can be fixed. Just unfortunate that we can't draft an PR on wiki.

**Comment by ChrisChinchilla** [comment]
https://github.com/ethresearch/eth-wiki/issues/10
