### ISSUE TITLE
'Subtleties' page wrongly states Ether is sent with reverting transaction

### ISSUE THREAD

**Issue by ColonelJ** [ethereum/wiki#665]
In https://github.com/ethereum/wiki/wiki/Subtleties it says if CALL (or CREATE) operations result in an exception then the Ether value is still sent (or lost).  This was confirmed not to be the case with this contract https://ropsten.etherscan.io/address/0x5c4360137246e114538fe132ae4f7abb5a215e8b where neither tryCall nor tryCreate functions reduce the amount of Ether in the contract.

Also see #49 which seems to highlight the same issue (there is no visible notice on the page that the information is outdated now).

**Comment by ChrisChinchilla** [comment]
Thanks @ColonelJ will take a look at this asap

**Comment by ChrisChinchilla** [comment]
https://github.com/ethresearch/eth-wiki/issues/11
