### ISSUE TITLE
“Ethereum Contract ABI” page has only JSON

### ISSUE THREAD

**Issue by geigerzaehler** [ethereum/wiki#667]
The “Ethereum Contract ABI” page only has the following JSON as content.

> [ { "constant": true, "inputs": [ { "name": "user", "type": "address" } ], "name": "accountLevel", "outputs": [ { "name": "", "type": "uint256" } ], "payable": false, "type": "function", "stateMutability": "view" } ]

It looks like a [former version](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI/59f929e8fe20bd83a01c539a5fe9a40197b83d5e) linking to the Solidity documentation should be restored.

**Comment by ChrisChinchilla** [comment]
Thanks @geigerzaehler done!
