### ISSUE TITLE
Broken links at ethereum/go-ethereum/wiki/geth

### ISSUE THREAD

**Issue by faustogut** [ethereum/wiki#669]
Hi @ChrisChinchilla !

I see what I think it's a bunch of broken links at https://github.com/ethereum/go-ethereum/wiki/geth

* ~on "Community and support -> Ethereum on social media": Wiki: http://wiki.ethereum.org~
* ~on "Community and support -> Ethereum on social media": Google+: http://google.com/+EthereumOrgOfficial~
* ~on "Community and support -> IRC": IRC Logs by ZeroGox ( https://zerogox.com/bot/log )~
* ~on "Community and support -> Forum": Forum ( https://forum.ethereum.org/categories/go-implementation )~
* ~on "Community and support -> The ZeroGox Bot": ZeroGox Bot ( https://zerogox.com/bot )~
* ~on "Community and support -> Dapp developers' mailing list": https://dapplist.net/~

**Comment by ChrisChinchilla** [comment]
Thanks @faustogut will look soon!

**Comment by ChrisChinchilla** [comment]
All resolved, soon to depreciate wiki anyway.
