### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by Jzarecta** [ethereum/wiki#67]
I installed the ethereum-serpent module from pip3 but it seems the package is not Python3 ready...

``` python
>>> import serpent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/serpent.py", line 225
    print json.dumps(o)
             ^
SyntaxError: invalid syntax
```

print is **print()** in python3 other errors also happened

``` python
>>> form serpent_setup import *
  File "<stdin>", line 1
    form serpent_setup import *
                     ^
SyntaxError: invalid syntax
```

**Comment by jamesray1** [comment]
Serpent is deprecated, use Vyper. FMI, see: Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
