### ISSUE TITLE
Ethash- nonce representation

### ISSUE THREAD

**Issue by BryceDoganer** [ethereum/wiki#671]
[Ethash - Main Loop](https://github.com/ethereum/wiki/wiki/Ethash#main-loop)

In the highlight below, the `nonce` is stated to be in big-endian format, yet after `nonce[::-1]` it states this is a little-endian representation. 

`nonce[::-1]` is then used in the code example. 

The text may need to be updated to: "`nonce[::-1]` is the eight-byte **big-endian** representation of that value."

![Screen Shot 2019-08-07 at 11 38 53 PM](https://user-images.githubusercontent.com/2391536/62673469-8d50cc80-b96c-11e9-8bc3-b30ece0cb93e.png)

![Screen Shot 2019-08-07 at 11 41 31 PM](https://user-images.githubusercontent.com/2391536/62673568-e6b8fb80-b96c-11e9-97c7-294ad702ea53.png)

**Comment by hjlee9182** [comment]
I think nonce is represented big endian, so isn't it little endian right when nonce[::-1] ( show reverse order) .

**Comment by ChrisChinchilla** [comment]
@hjlee9182 and @BryceDoganer Does this seem reasonable to you? Does this need fixing, or is everything correct?
