### ISSUE TITLE
eth_getBlockByHash missing receiptsRoot in the result object

### ISSUE THREAD

**Issue by taylorjdawson** [ethereum/wiki#672]
[eth_getblockbyhash](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash) is missing parameter, `receiptsRoot` in the result object. It is described in the params docs but not shown in the result object.

```
// Result
{
"id":1,
"jsonrpc":"2.0",
"result": {
   // receiptsRoot is missing here
  }
}
```

**Comment by ChrisChinchilla** [comment]
https://github.com/ethresearch/eth-wiki/issues/8
