### ISSUE TITLE
eth_getunclebyblockhashandindex typo

### ISSUE THREAD

**Issue by taylorjdawson** [ethereum/wiki#673]
[eth_getunclebyblockhashandindex](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getunclebyblockhashandindex)

The first param reads: 
> DATA, 32 Bytes - hash a block.

It might be better to write:
> DATA, 32 Bytes - The hash of a block.

https://github.com/ethereum/wiki/wiki/JSON-RPC#parameters-33

**Comment by ChrisChinchilla** [comment]
https://github.com/ethresearch/eth-wiki/issues/7
