### ISSUE TITLE
eth_getProof documentation is missing the address property in the returned object

### ISSUE THREAD

**Issue by nivida** [ethereum/wiki#679]
The documented JSON-RPC method ``eth_getProof`` does miss the ``address`` property in the [returned account object](https://github.com/ethereum/wiki/wiki/JSON-RPC#getproof-returns). I've double-checked the existence of the ``address`` property in the merged PRs of [parity](https://github.com/paritytech/parity/pull/9001) and [geth](https://github.com/ethereum/go-ethereum/pull/17737).

**Comment by hjlee9182** [comment]
![캡처](https://user-images.githubusercontent.com/46337218/69227207-d39d0500-0bc4-11ea-99dc-203223f85ed5.PNG)
Are you mean that this information?

**Comment by ChrisChinchilla** [comment]
As far as I can tell, this is correct and not an issue, but please let me know if that's incorrect.
