### ISSUE TITLE
The link for Ethereum Contract ABI under eth_call needs a reroute

### ISSUE THREAD

**Issue by tuckertranslator** [ethereum/wiki#686]
The link reference link for Ethereum Contract ABI under `eth_call` in the main wiki 
    (https://github.com/ethereum/wiki/wiki/json-rpc#eth_call) 
takes you to this wiki page: 
    https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI, 
which says:
    "This specification is now maintained as part of the Solidity documentation.", 
where this link is provided: 
    https://solidity.readthedocs.io/en/develop/abi-spec.html. 

It looks like it the wiki should be updated to reflect that. Maybe I should make a pull request?

**Comment by ChrisChinchilla** [comment]
@tuckertranslator Unfortunately you can't make PRs to GitHub wikis, but I'll get this fixed now, thanks!

**Comment by ChrisChinchilla** [comment]
Done!
