### ISSUE TITLE
Migrate the whitepaper to ethereum.org/whitepaper/

### ISSUE THREAD

**Issue by samajammin** [ethereum/wiki#695]
Hey folks - I've spoken to @ChrisChinchilla @jpitts @wtf & others on this but suggesting here that we update the [Whitepaper page](https://github.com/ethereum/wiki/wiki/White-Paper) to link to [ethereum.org/whitepaper/](https://ethereum.org/whitepaper/). Unfortunately GH wikis don't support 301 redirects, so I recommend we just update the page to something along the lines of:
```
This resource is now located at https://ethereum.org/whitepaper/
```
Or perhaps some more enticing overview / introduction to the paper, then linking to it.

You can find context on why we added the Whitepaper to ethereum.org here: https://github.com/ethereum/ethereum-org-website/issues/1011

**Comment by ChrisChinchilla** [comment]
@samajammin Yup. Just a couple of small things to sort with the new wiki, and then I will start adding disclaimers to all relevant pages.

**Comment by samajammin** [comment]
@ChrisChinchilla any update on this? Thanks in advance.

**Comment by ChrisChinchilla** [comment]
@samajammin Done here - https://github.com/ethereum/wiki/wiki/White-Paper

And updated all links in new wiki too, which should show up when we fix the deployment issues.

**Comment by samajammin** [comment]
Thanks @ChrisChinchilla! 🎉
