### ISSUE TITLE
No meta data displayed in search results

### ISSUE THREAD

**Issue by samajammin** [ethereum/wiki#702]
Currently shows no page information in search results:

![Image 2020-06-10 at 10 41 15 PM](https://user-images.githubusercontent.com/8097623/84349129-833ec200-ab6b-11ea-8071-dcabd7a98598.png)

![Image 2020-06-10 at 10 38 47 PM](https://user-images.githubusercontent.com/8097623/84349053-58ed0480-ab6b-11ea-9b0d-729bdba5bd56.png)

https://support.google.com/webmasters/answer/7489871?hl=en

**Comment by samajammin** [comment]
@ChrisChinchilla do you know of a way to control this? I Googled around for editing meta data for a Github wiki but couldn't find much.

**Comment by ChrisChinchilla** [comment]
@samajammin Frankly the whole GH wiki tool is kind of rubbish, so I doubt it, but I'll do a quick bot of research, or best longer time plan it somehow get the old links devalued and the new links to show up more in search results, but that could take time.

**Comment by ChrisChinchilla** [comment]
No, sadly, there's nothing we can do :(

**Comment by samajammin** [comment]
Bummer. Thanks for looking into it.

**Comment by samajammin** [comment]
[Pinged GH support on Twitter](https://twitter.com/samonchain/status/1271110209969123328?s=20), we'll see if they come up with any solutions.
