### ISSUE TITLE
[CapIncrease] Voting for capIncrease resolution failed due to "Error: not authorized to sign or already signed'

### ISSUE THREAD

**Issue by markledev** [ethereum/wiki#71]
![screen shot 2016-06-15 at 4 51 46 pm](https://cloud.githubusercontent.com/assets/10510973/16073643/8b8a66a4-3319-11e6-9755-6ce450911629.png)

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
