### ISSUE TITLE
For loop iterant increases unexpectedly

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/wiki#75]
https://gist.github.com/anonymous/5c95db33ac30e67ec5f8c4b05ae4b21a

Looks like it iterates an extra time unexpectedly

**Comment by jamesray1** [comment]
This is the expected behaviour with Solidity, some PLs do not enter the body of the loop in the last condition, others do.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
