### ISSUE TITLE
Please help, Ether has dissapeared or hacked?

### ISSUE THREAD

**Issue by etherwarrior** [ethereum/wiki#76]
Hello,

I am very new to Etherium and can really use some help. yesterday I was trying to use shapeshift.io to convert Ether to BTC, however the transactions never confirmed. I logged in to my wallet about 60 mins ago to test a transaction to another wallet. That worked (my only time i've successfully sent anything) , however my mist wallet went from have over 400 ether to only having 57.... I don't know what happened to them or  where to look to see what happened. Was my wallet hacked?

my mist address is: 0xDDe05c0fb7276644f524a4196d0C87A1a82287B8

I am grateful for any help, thank you

**Comment by bobsummerwill** [comment]
Hey @etherwarrior,

Sorry to hear about your issue, but this is an issue tracker for a Wiki.

You should contact ShapeShift's customer service directly with the details to get help.    Good luck!

**Comment by etherwarrior** [comment]
Thank you for your help @bobsummerwill
