### ISSUE TITLE
Missing ETH converted from BTC via Shapeshift

### ISSUE THREAD

**Issue by bbodien** [ethereum/wiki#82]
During the setup process, I converted BTC to ETH (1 ETH worth), but although I'm fully synced, with peers connected, my balance is 0.

I've contacted Shapeshift support and they've indicated that the transaction was processed correctly: https://etherscan.io/tx/0x3c5993e364f2ac2ab940190a24dfe01504c7414874f7fba05774f439bd06e950. 

The address is correct - am I doing something else wrong?

**Comment by alexvandesande** [comment]
Are you on the right chain? Is it possible that you are on Ethereum Classic or an older client?

**Comment by bbodien** [comment]
I'm using Ethereum Wallet version 0.8.1. How do I know which is the appropriate chain, and which one I'm on?

**Comment by TheRealWeeabo** [comment]
You need to sync the program with the block chain which will take a while but after that it should reflect your ether on your wallet.
