### ISSUE TITLE
0.8.1 Mist Crash -- Windows 10

### ISSUE THREAD

**Issue by sandybush** [ethereum/wiki#83]
For some reason, Mist will sync and then crash. I tried "launch application" prior to completing the sync and it crashes that way too. 

Recently had some trouble with launching Mist and not having my accounts be visible there--seemed to be able to fix that, but now this.

**Comment by ana0** [comment]
The same thing is happening to me with Mist 0.8.1 on Windows 7 64bit

**Comment by communitymotive** [comment]
In Windows7, Norton Security Suite - the version that is free to XFINITY/Comcast broadband customers, had to be over-ridden to open and it seemed two were not opened at all. The Ethereum connection was not completed, couldn't even use my pre-sale wallet, so I exited and am looking for some help.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
