### ISSUE TITLE
how to get value from solidity contract using java

### ISSUE THREAD

**Issue by friends110110** [ethereum/wiki#84]
my solidity contract is following:

```
contract SimpleStorage {
uint storedData;

function set(uint x) {
    storedData = x;
}

function get() constant returns (uint retVal) {
    return storedData;
}}
```

and generate the abi is following:

`[ { "constant": false, "inputs": [ { "name": "x", "type": "uint256" } ], "name": "set", "outputs": [], "type": "function" }, { "constant": true, "inputs": [], "name": "get", "outputs": [ { "name": "retVal", "type": "uint256", "value": "0" } ], "type": "function" } ]`
and referenced by https://github.com/ethereum/wiki/wiki/JSON-RPC,

How to invoke get funtion and get the value by using java (not js)?

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
