### ISSUE TITLE
Tx unconfirmed in Mist wallet/parity

### ISSUE THREAD

**Issue by nerdralph** [ethereum/wiki#86]
Using the mist wallet bundled with Parity 1.2.3.  None of my tx get confirmed, even with maximum gas/tx fee.  The highest I could choose for tx fee was .00067641, however the actual fee paid showing when I click on the tx was .00338205, with 105,000 gas used and .03221 eth per million gas.
The tx was a simple eth transfer from one account to another, no added data.
I had tried 3 other transactions previously with lower tx fees and none of them completed either.

p.s. I meant to open this against mist, and don't see any way of deleting it so I'll open an issue under mist and link to this.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
