### ISSUE TITLE
[eth] =✘= No instance name specified!

### ISSUE THREAD

**Issue by bellaj** [ethereum/wiki#87]
hello everybody,

I  am trying to run eth-netstats localy in order to monitor my nodes (i set up a private local blockchain with 2 nodes in a private network).
i followed the instruction provided in the doc but when i run `pm2 start app.json`
I get  this error : [eth] =✘= No instance name specified! 

i am runing geth with RPC and  my  app.json  is 

```
[
  {
    "name"              : "Nodeapp_",
    "script"            : "app.js",
    "log_date_format"   : "YYYY-MM-DD HH:mm Z",
    "merge_logs"        : false,
    "watch"             : false,
    "max_restarts"      : 10,
    "exec_interpreter"  : "node",
    "exec_mode"         : "fork_mode",
    "env":
    {
      "NODE_ENV"        : "production",
      "RPC_HOST"        : "localhost",
      "RPC_PORT"        : "8000",
      "LISTENING_PORT"  : "30303",
      "INSTANCE_NAME"   : "",
      "CONTACT_DETAILS" : "",
      "WS_SERVER"       : "wss://rpc.ethstats.net",
      "WS_SECRET"       : "so8ku5jeza8du5tu",
      "VERBOSITY"       : 2
    }
  }
]

```

**Comment by bellaj** [comment]
even if i define a INSTANCE_NAME the problem remain

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
