### ISSUE TITLE
Test Net 

### ISSUE THREAD

**Issue by AlphaQUp717** [ethereum/wiki#88]
hello if someone can help me out I have been mining and for some reason the ETH I gotten from it wont let me transfer to my coinbase wallet or even my main mist wallet (not my mining wallet) not to sure what to do I just wanted to see if I can really receive the funds.
![vv](https://cloud.githubusercontent.com/assets/18385021/17563799/f298cb7c-5efe-11e6-9028-701eb9a5df82.jpg)
![vvv](https://cloud.githubusercontent.com/assets/18385021/17563804/f6950e98-5efe-11e6-90bf-e1a86f1ec360.jpg)

**Comment by bellaj** [comment]
Coinbase or etherbase (they are the same thing)  try to  creat a add a new account and send it the ETH

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
