### ISSUE TITLE
Clarify "main Ethereum Specification"

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/wiki#90]
> The items in the list (following the first item 0x12) are transactions in the format described in the main Ethereum specification

https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol

What specification is this referring to?

**Comment by bobsummerwill** [comment]
Yellow Paper, perhaps, @aakilfernandes?

**Comment by aakilfernandes** [comment]
Possibly. Would be nice to get a more specific link (for example with a paragraph number). The same is true for

> block headers in the format described in the main Ethereum specification

> blocks, minus the header, in the format described in the main Ethereum specification

**Comment by realcodywburns** [comment]
Section 4.3 and appendix f in the yellow paper address the format of transactions. gavwood.com/paper.PDF is a link to the yellow paper.

**Comment by aakilfernandes** [comment]
Got it. Thanks @realcodywburns

**Comment by akvadrako** [comment]
Why is this closed? In the Wire Protocol, this still isn't clarified.
