### ISSUE TITLE
account is locked

### ISSUE THREAD

**Issue by yuzhiyou1990** [ethereum/wiki#91]
Request:
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{ "from": "0x7390328296e8bd528ec6c7b8ee3348fe98192977", "to": "0xc7e64856B8f2C8F1AbA74B7a9fAeB74F24300232", "value": "0x00033","data":"0x60fe47b10000000000000000000000000000000000000000000000000000000000000021" }],"id":1}' localhost:8545

Response:
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"account is locked"}}

How to unlock?

**Comment by mario02423** [comment]
Please see http://ethereum.stackexchange.com/questions/4582/error-account-is-locked-attempting-to-send-ether-from-one-account-to-another

**Comment by lesyk** [comment]
`let accountUnlocked = web3.personal.unlockAccount(address, passphrase);`
