### ISSUE TITLE
Fixed type confusion

### ISSUE THREAD

**Issue by mrhornsby** [ethereum/wiki#92]
Hi,

I was looking at the [ABI specification](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI) and it seems to be inconsistent in how to interpret the fixedMxN type. In the [Types](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#types) section we have:

```
fixed<M>x<N>: fixed-point signed number of M+N bits, 0 < M + N <= 256, M % 8 == N % 8 == 0. Corresponds to the int256 equivalent binary value divided by 2^M.
```

While in the [Formal Specification of Encoding](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#formal-specification-of-the-encoding) section we have:

```
fixed<M>x<N>: enc(X) is enc(X * 2**N) where X * 2**N is interpreted as a int256.
```

The former suggests that _M_ is the size of the fractional part and while the latter suggests that _N_ is the size of the fractional part. The latter form makes more sense in my mind, but I wanted to make sure everyone agrees.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
