### ISSUE TITLE
Clarify reverse in GetBlockHeaders

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/wiki#93]
> Reply must contain a number of block headers, of rising number when reverse is 0, falling when 1

So if i request

start: 10,
maxBlocks: 10
skip: 0
reverse: 1

Does my peer return
1. blocks (20, 10]
   or
2. blocks [10, 0)

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
