### ISSUE TITLE
Gas price

### ISSUE THREAD

**Issue by alesl** [ethereum/wiki#99]
Not sure if doing something wrong, but it appears that gasPrice is wrong or it is calculated based on too many recent blocks. At the moment it is reported as 23710649647, but most current transactions has gas price much higher: 37164430447.

**Comment by pooleja** [comment]
I am seeing inconsistent gas price as well:
```
var gasPrice = web3.eth.gasPrice;
console.log(gasPrice.toString(10)); // "20000000000"
```
But when I calculate it in unit tests based on a transaction that is being made, it is evaluating to:
```
 100000000000 * transaction.receipt.gasUsed
```
Not sure if I am mis-using the api but I came here to see if anyone else had reported issues with gas price.

**Comment by jamesray1** [comment]
Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
